'use client';
import React,{useEffect,useMemo,useState} from 'react';
import {Check,Printer,Share2,RotateCcw} from 'lucide-react';
import type {ToolMeta} from '@/data/toolsRegistry';

const card='relative w-full max-w-5xl mx-auto overflow-hidden rounded-[28px] border border-amber-200/80 dark:border-amber-400/10 bg-gradient-to-br from-white via-amber-50/25 to-orange-50/20 dark:from-zinc-900/95 dark:via-zinc-900/95 dark:to-amber-950/10 p-5 sm:p-7 space-y-6 shadow-[0_24px_80px_-36px_rgba(0,0,0,0.45)]';
const input='w-full rounded-2xl border border-zinc-200/90 dark:border-white/10 bg-zinc-50/80 dark:bg-zinc-950/80 px-4 py-3.5 text-sm text-zinc-900 dark:text-white outline-none focus:border-violet-500/70 focus:ring-4 focus:ring-violet-500/10';
const btn='inline-flex items-center justify-center gap-2 rounded-2xl bg-violet-600 px-5 py-3 text-xs font-bold text-white hover:bg-violet-500';
const sec='inline-flex items-center justify-center gap-2 rounded-2xl border border-zinc-200 dark:border-white/10 bg-white dark:bg-zinc-900 px-4 py-3 text-xs font-semibold';
const N=({label,v,set,min=0}:{label:string;v:string;set:(x:string)=>void;min?:number})=><label className="block"><span className="mb-2 block text-xs font-semibold text-zinc-600 dark:text-zinc-300">{label}</span><input className={input} type="number" min={min} value={v} onChange={e=>set(e.target.value)}/></label>;

const colors=[
['Oct 11','Orange','Warmth, energy and enthusiasm'],['Oct 12','White','Purity, peace and calm'],['Oct 13','Red','Strength, passion and energy'],['Oct 14','Royal Blue','Confidence, stability and grandeur'],['Oct 15','Yellow','Happiness, brightness and optimism'],['Oct 16','Green','Growth, renewal and harmony'],['Oct 17','Grey','Balance and a grounded festive style'],['Oct 18','Purple','Richness, dignity and elegance'],['Oct 19','Peacock Green','Freshness, individuality and vibrancy']
];

function Navratri(){const idx=useMemo(()=>{const n=new Date(),s=new Date('2026-10-11'),e=new Date('2026-10-19T23:59:59');return n>=s&&n<=e?Math.floor((n.getTime()-s.getTime())/86400000):-1},[]);
return <div className={card}><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-amber-700 dark:text-amber-300"><span aria-hidden="true">🪔</span> Festival Planner</div><div className="rounded-2xl bg-violet-50 dark:bg-violet-950/20 p-5"><b>Sharad Navratri 2026</b><p className="mt-1 text-sm text-zinc-500">October 11–19, 2026 · 9-day color calendar</p><p className="mt-3 text-lg font-black">{idx>=0?'Today’s color: '+colors[idx][1]:'2026 color calendar'}</p></div><div className="grid gap-3">{colors.map((x,i)=><div key={x[0]} className={'rounded-2xl border p-4 '+(i===idx?'border-violet-500 bg-violet-50 dark:bg-violet-950/20':'border-zinc-200 dark:border-zinc-800')}><p className="text-sm font-bold">Day {i+1} · {x[0]} · {x[1]}</p><p className="mt-1 text-xs text-zinc-500 dark:text-zinc-400">{x[2]}</p></div>)}</div></div>}

function Mithai(){const[a,sa]=useState('4'),[c,sc]=useState('2'),[g,sg]=useState('4'),[gift,sgift]=useState('2'),[v,sv]=useState('4'),[f,sf]=useState('5');const people=+a+(+c*.6)+ +g,total=Math.max(0,people*.125+(+gift*.225)),faral=people*.14;return <div className={card}><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-amber-700 dark:text-amber-300"><span aria-hidden="true">🪔</span> Festival Planner</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><N label="Adults at home" v={a} set={sa}/><N label="Children at home" v={c} set={sc}/><N label="Guests" v={g} set={sg}/><N label="Gift recipients / boxes" v={gift} set={sgift}/><N label="Sweet varieties" v={v} set={sv} min={1}/><N label="Faral varieties" v={f} set={sf} min={1}/></div><div className="grid md:grid-cols-2 gap-4"><div className="rounded-2xl bg-violet-50 dark:bg-violet-950/20 p-5"><p className="text-xs text-zinc-500">Estimated sweets</p><b className="text-3xl">{total.toFixed(2)} kg</b><p className="text-xs text-zinc-500 mt-2">{(+v?total/+v:0).toFixed(2)} kg per sweet variety.</p></div><div className="rounded-2xl bg-amber-50 dark:bg-amber-950/20 p-5"><p className="text-xs text-zinc-500">Estimated faral</p><b className="text-3xl">{faral.toFixed(2)} kg</b><p className="text-xs text-zinc-500 mt-2">{(+f?faral/+f:0).toFixed(2)} kg per faral variety.</p></div></div><p className="text-xs text-zinc-500">Planning estimate only; serving sizes, appetite, meals and gifting habits vary.</p></div>}

const items=['Lakshmi idol','Ganesha idol','Kalash','Coconut','Roli / Kumkum','Akshat (rice)','Flowers','Diyas','Cotton wicks','Oil or ghee','Incense sticks','Camphor','Fruits','Sweets','Puja thali','Clean cloth'];
function Puja(){const[x,setX]=useState<string[]>([]),toggle=(s:string)=>setX(v=>v.includes(s)?v.filter(a=>a!==s):[...v,s]);const share=()=>{const t='Diwali Puja Checklist\n'+items.map(s=>(x.includes(s)?'✓ ':'☐ ')+s).join('\n');navigator.share?navigator.share({title:'Diwali Puja Checklist',text:t}):navigator.clipboard?.writeText(t)};return <div className={card}><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-amber-700 dark:text-amber-300"><span aria-hidden="true">🪔</span> Puja Checklist</div><div className="flex flex-wrap gap-2"><button className={btn} onClick={()=>setX(items)}><Check className="h-4 w-4"/>Select all</button><button className={sec} onClick={()=>setX([])}><RotateCcw className="h-4 w-4"/>Clear</button><button className={sec} onClick={()=>window.print()}><Printer className="h-4 w-4"/>Print</button><button className={sec} onClick={share}><Share2 className="h-4 w-4"/>Share</button></div><div className="grid sm:grid-cols-2 gap-3">{items.map(s=><button key={s} onClick={()=>toggle(s)} className={'flex gap-3 items-center rounded-2xl border p-4 text-left '+(x.includes(s)?'border-emerald-500 bg-emerald-50 dark:bg-emerald-950/20':'border-zinc-200 dark:border-zinc-800')}><span className="h-6 w-6 rounded-lg border flex items-center justify-center">{x.includes(s)?'✓':''}</span><span className="text-sm font-semibold">{s}</span></button>)}</div><p className="text-xs text-zinc-500">{x.length} of {items.length} checked.</p></div>}

function Budget(){const ls=['Gifts','Clothes','Mithai & Faral','Decoration','Diyas & Lights','Puja','Travel','Food','Other'],[v,setV]=useState<Record<string,string>>({});const total=ls.reduce((s,k)=>s+(+v[k]||0),0);return <div className={card}><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-amber-700 dark:text-amber-300"><span aria-hidden="true">🪔</span> Diwali Budget</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{ls.map(k=><label key={k}><span className="mb-2 block text-xs font-semibold">{k} (₹)</span><input className={input} type="number" min="0" value={v[k]||''} onChange={e=>setV(a=>({...a,[k]:e.target.value}))}/></label>)}</div><div className="rounded-2xl bg-violet-50 dark:bg-violet-950/20 p-5"><p className="text-xs text-zinc-500">Estimated Diwali budget</p><b className="text-3xl">₹{total.toLocaleString('en-IN')}</b></div></div>}

function Diya(){const[r,sr]=useState('4'),[d,sd]=useState('2'),[w,sw]=useState('6'),[p,sp]=useState('5'),[x,sx]=useState('10'),[h,sh]=useState('4');const total=+r*4+ +d*2+ +w+ +p+ +x;return <div className={card}><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-amber-700 dark:text-amber-300"><span aria-hidden="true">🪔</span> Diwali Lighting</div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><N label="Rooms" v={r} set={sr}/><N label="Doors" v={d} set={sd}/><N label="Windows / balconies" v={w} set={sw}/><N label="Puja diyas" v={p} set={sp}/><N label="Decorative diyas" v={x} set={sx}/><N label="Burning hours" v={h} set={sh} min={1}/></div><div className="grid sm:grid-cols-2 gap-4"><div className="rounded-2xl bg-amber-50 dark:bg-amber-950/20 p-5"><p className="text-xs text-zinc-500">Estimated diyas</p><b className="text-3xl">{total}</b></div><div className="rounded-2xl bg-violet-50 dark:bg-violet-950/20 p-5"><p className="text-xs text-zinc-500">Approx. oil / ghee planning</p><b className="text-3xl">{(total*(+h)*7/1000).toFixed(2)} L</b></div></div><p className="text-xs text-zinc-500">Fuel use varies by diya size, wick and conditions. Keep open flames attended.</p></div>}

function Cleaning(){const[days,setDays]=useState('10');const tasks=['Declutter rooms and storage','Deep-clean kitchen','Clean fans, windows and doors','Wash curtains / soft furnishings','Clean puja area','Organize wardrobes','Clean balcony / entrance','Buy cleaning supplies','Final dusting and mopping'];const dayCount=Math.max(1,Math.min(30,Math.floor(+days)||1));const perDay=Math.ceil(tasks.length/dayCount);const groups=Array.from({length:Math.min(dayCount,tasks.length)},(_,i)=>tasks.slice(i*perDay,(i+1)*perDay)).filter(g=>g.length);return <div className={card}><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-amber-700 dark:text-amber-300"><span aria-hidden="true">🪔</span> Diwali Safai Planner</div><div className="max-w-xs"><N label="Days available before Diwali" v={days} set={setDays} min={1}/></div><div className="space-y-3">{groups.map((group,i)=><div key={i} className="rounded-2xl border border-zinc-200 dark:border-zinc-800 p-4"><p className="text-xs font-bold uppercase tracking-wider text-violet-600">Day {i+1}</p><div className="mt-2 space-y-2">{group.map((t,j)=><div key={t} className="flex gap-3"><b>{i*perDay+j+1}.</b><span className="text-sm font-semibold">{t}</span></div>)}</div></div>)}</div></div>}

function Countdown(){const target=new Date('2026-11-08T00:00:00').getTime(),[now,setNow]=useState(()=>Date.now());useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),60000);return()=>window.clearInterval(id)},[]);const days=Math.max(0,Math.ceil((target-now)/86400000));return <div className={card}><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[0.18em] text-amber-700 dark:text-amber-300"><span aria-hidden="true">🪔</span> Diwali Preparation</div><div className="rounded-3xl bg-zinc-950 text-white p-8 text-center"><p className="text-xs uppercase tracking-widest text-violet-300">Diwali 2026</p><b className="block text-6xl mt-2">{days}</b><p className="text-sm text-zinc-400">days until November 8, 2026</p></div><div className="space-y-3">{[['10–14 days before','Deep cleaning + decluttering'],['7–10 days before','Gifts, clothes and decoration shopping'],['3–5 days before','Mithai/faral preparation'],['1–2 days before','Puja supplies + final cleaning'],['Diwali day','Lakshmi Puja and family preparations']].map(x=><div key={x[0]} className="rounded-2xl border border-zinc-200 dark:border-zinc-800 p-4"><b className="text-xs text-violet-600">{x[0]}</b><p className="mt-1 text-sm font-semibold">{x[1]}</p></div>)}</div></div>}

export default function FestivalEngine({tool}:{tool:ToolMeta}){switch(tool.slug){case'navratri-colors-2026':return <Navratri/>;case'diwali-mithai-faral-calculator':return <Mithai/>;case'diwali-puja-samagri-checklist':return <Puja/>;case'diwali-budget-calculator':return <Budget/>;case'diya-requirement-calculator':return <Diya/>;case'diwali-cleaning-planner':return <Cleaning/>;case'diwali-countdown-preparation-planner':return <Countdown/>;default:return null}}
