'use client';
import React,{useEffect,useRef,useState} from 'react';
import QRCode from 'qrcode';

const card='w-full max-w-5xl mx-auto rounded-3xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 sm:p-8 space-y-5';
const input='w-full rounded-xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-950 px-4 py-3 text-sm text-zinc-900 dark:text-white';
function download(url:string,name:string){const a=document.createElement('a');a.href=url;a.download=name;a.click();}

export default function ImageEngine({toolSlug,toolName}:{toolSlug:string;toolName:string}){
 const [file,setFile]=useState<File|null>(null),[src,setSrc]=useState(''),[quality,setQuality]=useState(85),[width,setWidth]=useState(1200),[height,setHeight]=useState(800),[ratio,setRatio]=useState('free'),[x,setX]=useState(50),[y,setY]=useState(50),[angle,setAngle]=useState(0),[flip,setFlip]=useState('none'),[text,setText]=useState('https://example.com'),[output,setOutput]=useState(''),[palette,setPalette]=useState<string[]>([]),[message,setMessage]=useState('');
 const canvas=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{if(file){if(file.size>50*1024*1024){setMessage('Image must be 50 MB or smaller.');return;}const r=new FileReader();r.onload=()=>setSrc(String(r.result));r.readAsDataURL(file);}},[file]);
 const make=async()=>{setMessage('');if(toolSlug==='instant-qr-code-generator'){setOutput(await QRCode.toDataURL(text,{width:1000,margin:2}));return;}if(!src){setMessage('Choose an image first.');return;}const img=new Image();img.onload=()=>{let ow=img.width,oh=img.height;let tw=ow,th=oh;if(toolSlug==='image-resizer'){tw=Math.max(1,width);th=Math.max(1,height);}else if(toolSlug==='crop-image-online'){let ar=ratio==='1:1'?1:ratio==='4:3'?4/3:ratio==='16:9'?16/9:ow/oh; if(ratio!=='free'){if(ow/oh>ar){th=oh;tw=Math.round(oh*ar)}else{tw=ow;th=Math.round(ow/ar)}}else{tw=Math.min(width,ow);th=Math.min(height,oh)}}else if(['webp-to-png-converter','webp-to-jpg-converter','png-to-jpg-converter','jpg-to-png-converter','svg-to-png-converter'].includes(toolSlug)){tw=ow;th=oh;}const c=canvas.current!;c.width=tw;c.height=th;const ctx=c.getContext('2d')!;ctx.clearRect(0,0,tw,th);let filter='none';if(toolSlug==='black-and-white-image-filter')filter='grayscale(1)';if(toolSlug==='invert-image-colors')filter='invert(1)';if(toolSlug==='image-blur-filter')filter='blur(8px)';ctx.filter=filter;ctx.save();ctx.translate(tw/2,th/2);ctx.rotate(angle*Math.PI/180);ctx.scale(flip==='horizontal'?-1:1,flip==='vertical'?-1:1);ctx.translate(-tw/2,-th/2);let sx=0,sy=0,sw=ow,sh=oh;if(toolSlug==='crop-image-online'){sw=tw;sh=th;sx=Math.round((ow-sw)*x/100);sy=Math.round((oh-sh)*y/100);}ctx.drawImage(img,sx,sy,sw,sh,0,0,tw,th);ctx.restore();let type=toolSlug==='webp-to-png-converter'||toolSlug==='jpg-to-png-converter'||toolSlug==='svg-to-png-converter'?'image/png':'image/jpeg';if(toolSlug==='webp-to-jpg-converter'||toolSlug==='png-to-jpg-converter')type='image/jpeg';const url=c.toDataURL(type,quality/100);setOutput(url);if(toolSlug==='image-color-palette-extractor'){const d=ctx.getImageData(0,0,tw,th).data;const map=new Map<string,number>();for(let i=0;i<d.length;i+=40){const k=[d[i],d[i+1],d[i+2]].map(v=>Math.round(v/16)*16).join(',');map.set(k,(map.get(k)||0)+1)}setPalette([...map.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k])=>'#'+k.split(',').map(v=>Number(v).toString(16).padStart(2,'0')).join('')))} };img.src=src;};
 const accept=toolSlug==='svg-to-png-converter'?'.svg,image/svg+xml':'image/*';
 if(toolSlug==='instant-qr-code-generator')return <div className={card}><input className={input} value={text} onChange={e=>setText(e.target.value)} placeholder="Text or URL"/><button className="rounded-xl bg-violet-600 px-5 py-2.5 text-xs font-bold text-white" onClick={make}>Generate QR</button>{output&&<div><img className="max-w-xs rounded-2xl" src={output}/><button className="mt-3 rounded-xl border px-4 py-2 text-xs" onClick={()=>download(output,'qrcode.png')}>Download</button></div>}</div>;
 return <div className={card}><input type="file" accept={accept} onChange={e=>setFile(e.target.files?.[0]||null)} className="text-sm"/>{message&&<p className="text-sm text-rose-500">{message}</p>}{src&&<div className="grid sm:grid-cols-2 gap-3">{['image-resizer','crop-image-online'].includes(toolSlug)&&<><input className={input} type="number" value={width} onChange={e=>setWidth(Number(e.target.value))} placeholder="Width"/><input className={input} type="number" value={height} onChange={e=>setHeight(Number(e.target.value))} placeholder="Height"/></>}{toolSlug==='crop-image-online'&&<><select className={input} value={ratio} onChange={e=>setRatio(e.target.value)}><option value="free">Free</option><option value="1:1">1:1</option><option value="4:3">4:3</option><option value="16:9">16:9</option></select><input className={input} type="range" min="0" max="100" value={x} onChange={e=>setX(Number(e.target.value))}/><input className={input} type="range" min="0" max="100" value={y} onChange={e=>setY(Number(e.target.value))}/></>}{toolSlug==='flip-rotate-image'&&<><select className={input} value={flip} onChange={e=>setFlip(e.target.value)}><option value="none">No flip</option><option value="horizontal">Flip horizontal</option><option value="vertical">Flip vertical</option></select><input className={input} type="number" step="90" value={angle} onChange={e=>setAngle(Number(e.target.value))}/></>}{['compress-image','webp-to-jpg-converter','png-to-jpg-converter'].includes(toolSlug)&&<input className={input} type="range" min="10" max="100" value={quality} onChange={e=>setQuality(Number(e.target.value))}/>}</div>}<button className="rounded-xl bg-violet-600 px-5 py-2.5 text-xs font-bold text-white" onClick={make}>Process {toolName}</button>{output&&<div><img className="max-h-96 max-w-full rounded-2xl border" src={output}/><button className="mt-3 rounded-xl border px-4 py-2 text-xs" onClick={()=>download(output,`${toolSlug}.${output.startsWith('data:image/png')?'png':'jpg'}`)}>Download</button></div>}{palette.length>0&&<div className="flex flex-wrap gap-2">{palette.map(c=><div key={c} className="rounded-xl border px-3 py-2 text-xs font-mono">{c}</div>)}</div>}</div>;
}
