'use client';
import React,{useState} from 'react';
import {PDFDocument,StandardFonts,rgb,degrees} from 'pdf-lib';
import JSZip from 'jszip';
import {Upload,Download,ArrowUp,ArrowDown,Trash2,Loader2,ShieldAlert} from 'lucide-react';

const card='w-full max-w-5xl mx-auto rounded-3xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 sm:p-8 space-y-5 shadow-sm';
const input='w-full rounded-xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-950 px-4 py-3 text-sm text-zinc-900 dark:text-white';
const MAX=100*1024*1024, MAX_FILES=20;
function save(bytes:Uint8Array,name:string,type:string){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([bytes as any],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function renderPdf(file:File,scale=1.5,gray=false){const pdfjs:any=await import('pdfjs-dist/legacy/build/pdf.mjs');const data=new Uint8Array(await file.arrayBuffer());const doc=await pdfjs.getDocument({data,disableWorker:true}).promise;const pages:{blob:Blob;w:number;h:number}[]=[];for(let i=1;i<=doc.numPages;i++){const p=await doc.getPage(i),vp=p.getViewport({scale});const c=document.createElement('canvas');c.width=Math.ceil(vp.width);c.height=Math.ceil(vp.height);const ctx=c.getContext('2d')!;if(gray)ctx.filter='grayscale(1)';await p.render({canvasContext:ctx,viewport:vp}).promise;const blob:Blob=await new Promise(r=>c.toBlob(b=>r(b!),'image/jpeg',.9));pages.push({blob,w:c.width,h:c.height})}return pages}
async function pdfToDocx(file:File){const pdfjs:any=await import('pdfjs-dist/legacy/build/pdf.mjs');const doc=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer()),disableWorker:true}).promise;let body='';for(let i=1;i<=doc.numPages;i++){const page=await doc.getPage(i);const tc=await page.getTextContent();const text=tc.items.map((x:any)=>x.str).join(' ').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;');body+=`<w:p><w:r><w:t xml:space="preserve">${text}</w:t></w:r></w:p>`}const zip=new JSZip();zip.file('[Content_Types].xml','<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>');zip.file('_rels/.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>');zip.file('word/document.xml',`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main"><w:body>${body}<w:sectPr><w:pgSz w:w="12240" w:h="15840"/><w:pgMar w:top="1440" w:right="1440" w:bottom="1440" w:left="1440"/></w:sectPr></w:body></w:document>`);return zip.generateAsync({type:'uint8array'});}
async function docxToPdf(file:File){const zip=await JSZip.loadAsync(await file.arrayBuffer());const xml=await zip.file('word/document.xml')?.async('string');if(!xml)throw new Error('Valid DOCX document.xml was not found.');const text=xml.replace(/<w:tab\s*\/?>/g,'\t').replace(/<w:br\s*\/?>/g,'\n').replace(/<\/w:p>/g,'\n').replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>');const pdf=await PDFDocument.create();const font=await pdf.embedFont(StandardFonts.Helvetica);let page=pdf.addPage([612,792]);let y=750;const lines=text.split(/\r?\n/);for(const raw of lines){const words=raw.split(/\s+/);let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(test,11)>500){if(y<50){page=pdf.addPage([612,792]);y=750}page.drawText(line,{x:55,y,size:11,font});y-=16;line=word}else line=test}if(y<50){page=pdf.addPage([612,792]);y=750}page.drawText(line,{x:55,y,size:11,font});y-=16}return pdf.save();}

export default function PdfEngine({toolSlug,toolName}:{toolSlug:string;toolName:string}){
 const [files,setFiles]=useState<File[]>([]),[processing,setProcessing]=useState(false),[error,setError]=useState(''),[pageSpec,setPageSpec]=useState('1'),[order,setOrder]=useState(''),[angle,setAngle]=useState('90'),[output,setOutput]=useState<Uint8Array|null>(null),[input2,setInput2]=useState('');
 const add=(e:React.ChangeEvent<HTMLInputElement>)=>{const incoming=[...(e.target.files||[])];const ok=incoming.filter(f=>f.type==='application/pdf'||(toolSlug==='jpg-to-pdf'&&f.type.startsWith('image/'))||(toolSlug==='word-to-pdf'&&f.name.toLowerCase().endsWith('.docx')));if(ok.length+files.length>MAX_FILES){setError(`Maximum ${MAX_FILES} files.`);return}if(ok.reduce((s,f)=>s+f.size,0)+files.reduce((s,f)=>s+f.size,0)>MAX){setError('Selected files exceed the 100 MB browser-processing limit.');return}setFiles(p=>[...p,...ok]);setError('')};
 const run=async()=>{if(!files.length){setError('Select a file first.');return}setProcessing(true);setError('');try{if(toolSlug==='protect-pdf-password'){if(!input2)throw new Error('Enter a password.');const mod:any=await import('pdfstudio');const toolkit=await mod.createPdfToolkit();setOutput(await toolkit.lock(files[0],{userPassword:input2}));return;} if(toolSlug==='unlock-pdf-password'){if(!input2)throw new Error('Enter the PDF password.');const mod:any=await import('pdfstudio');const toolkit=await mod.createPdfToolkit();setOutput(await toolkit.unlock(files[0],{password:input2}));return;}
  if(toolSlug==='pdf-to-jpg'||toolSlug==='pdf-grayscale-converter'){const pages=await renderPdf(files[0],1.5,toolSlug==='pdf-grayscale-converter');if(toolSlug==='pdf-to-jpg'){const z=new JSZip();pages.forEach((p,i)=>z.file(`page-${i+1}.jpg`,p.blob));const b=await z.generateAsync({type:'uint8array'});save(b,'pdf-pages-jpg.zip','application/zip');return}else{const p=await PDFDocument.create();for(const item of pages){const bytes=new Uint8Array(await item.blob.arrayBuffer());const img=await p.embedJpg(bytes);const pg=p.addPage([img.width,img.height]);pg.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}setOutput(await p.save());return}}
  if(toolSlug==='pdf-to-word'){setOutput(await pdfToDocx(files[0]));return}
  if(toolSlug==='word-to-pdf'){setOutput(await docxToPdf(files[0]));return}
  if(toolSlug==='jpg-to-pdf'){const p=await PDFDocument.create();for(const f of files){const b=new Uint8Array(await f.arrayBuffer());const img=f.type==='image/png'?await p.embedPng(b):await p.embedJpg(b);const pg=p.addPage([img.width,img.height]);pg.drawImage(img,{x:0,y:0,width:img.width,height:img.height})}setOutput(await p.save());return}
  const pdf=await PDFDocument.load(await files[0].arrayBuffer());const count=pdf.getPageCount();
  const parsePages=(s:string)=>{const out:number[]=[];for(const part of s.split(',').map(x=>x.trim()).filter(Boolean)){if(/^\d+$/.test(part)){const n=Number(part)-1;if(n<0||n>=count)throw new Error(`Page ${n+1} is outside the PDF.`);out.push(n)}else if(/^(\d+)-(\d+)$/.test(part)){const [,a,b]=part.match(/^(\d+)-(\d+)$/)!;const start=Number(a),end=Number(b);if(start<1||end>count||start>end)throw new Error('Invalid page range.');for(let n=start;n<=end;n++)out.push(n-1)}else throw new Error('Use page numbers like 1,3-5.')}return Array.from(new Set(out))};
  if(toolSlug==='split-pdf'||toolSlug==='delete-pdf-pages'||toolSlug==='reorder-pdf-pages'){const idx=toolSlug==='reorder-pdf-pages'?parsePages(order||pageSpec):toolSlug==='delete-pdf-pages'?pdf.getPageIndices().filter(i=>!parsePages(pageSpec).includes(i)):parsePages(pageSpec);if(toolSlug==='reorder-pdf-pages'&&idx.length!==count)throw new Error('Reorder requires every page exactly once.');const outPdf=await PDFDocument.create();(await outPdf.copyPages(pdf,idx)).forEach(p=>outPdf.addPage(p));setOutput(await outPdf.save());return}
  if(toolSlug==='rotate-pdf'){const pages=pageSpec.trim().toLowerCase()==='all'?pdf.getPageIndices():parsePages(pageSpec);pages.forEach(i=>pdf.getPage(i).setRotation(degrees(Number(angle)||90)));setOutput(await pdf.save());return}
  if(toolSlug==='add-page-numbers-pdf'){const font=await pdf.embedFont(StandardFonts.Helvetica);pdf.getPages().forEach((p,i)=>{const text=`${i+1} / ${count}`;p.drawText(text,{x:p.getWidth()/2-20,y:20,size:9,font,color:rgb(.3,.3,.3)})});setOutput(await pdf.save());return}
  if(toolSlug==='compress-pdf'){setOutput(await pdf.save({useObjectStreams:true,addDefaultPage:false}));return}
  if(toolSlug==='merge-pdf'){const outPdf=await PDFDocument.create();for(const f of files){const src=await PDFDocument.load(await f.arrayBuffer());(await outPdf.copyPages(src,src.getPageIndices())).forEach(p=>outPdf.addPage(p))}setOutput(await outPdf.save());return}
 }catch(e){setError(e instanceof Error?e.message:'PDF processing failed.')}finally{setProcessing(false)}};
 const move=(i:number,d:number)=>{const a=[...files],j=i+d;if(j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];setFiles(a)};
 return <div className={card}><input type="file" multiple={toolSlug==='merge-pdf'||toolSlug==='jpg-to-pdf'} accept={toolSlug==='jpg-to-pdf'?'image/jpeg,image/png':toolSlug==='word-to-pdf'?'.docx':'.pdf'} onChange={add}/>{error&&<div className="flex gap-2 text-sm text-rose-500"><ShieldAlert className="h-4 w-4"/>{error}</div>}<div className="space-y-2">{files.map((f,i)=><div key={`${f.name}-${i}`} className="flex items-center justify-between rounded-xl border p-3 text-xs"><span className="truncate">{f.name}</span><div className="flex gap-1"><button className="border rounded p-1" onClick={()=>move(i,-1)}><ArrowUp className="h-3 w-3"/></button><button className="border rounded p-1" onClick={()=>move(i,1)}><ArrowDown className="h-3 w-3"/></button><button className="border rounded p-1" onClick={()=>setFiles(files.filter((_,j)=>j!==i))}><Trash2 className="h-3 w-3"/></button></div></div>)}</div>{['split-pdf','delete-pdf-pages','rotate-pdf'].includes(toolSlug)&&<input className={input} value={pageSpec} onChange={e=>setPageSpec(e.target.value)} placeholder="Pages: 1,3-5 (rotate can use all)"/>}{toolSlug==='reorder-pdf-pages'&&<input className={input} value={order} onChange={e=>setOrder(e.target.value)} placeholder="Complete order, e.g. 3,1,2"/>}{toolSlug==='rotate-pdf'&&<input className={input} value={angle} onChange={e=>setAngle(e.target.value)} placeholder="Rotation: 90, 180, 270"/>}{['protect-pdf-password','unlock-pdf-password'].includes(toolSlug)&&<input className={input} type="password" value={input2} onChange={e=>setInput2(e.target.value)} placeholder={toolSlug==='protect-pdf-password'?'Password to protect PDF':'Password to unlock PDF'}/>}<button className="rounded-xl bg-violet-600 px-5 py-3 text-xs font-bold text-white disabled:opacity-50" disabled={processing} onClick={run}>{processing?<><Loader2 className="inline h-4 w-4 animate-spin"/> Processing...</>:`Run ${toolName}`}</button>{output&&<button className="ml-2 rounded-xl border px-4 py-3 text-xs font-bold" onClick={()=>save(output,`${toolSlug}.${toolSlug==='pdf-to-word'?'docx':toolSlug==='word-to-pdf'||toolSlug.includes('pdf')?'pdf':'bin'}`,toolSlug==='pdf-to-word'?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'application/pdf')}><Download className="inline h-4 w-4"/> Download</button>}</div>;
}
