'use client';

import React,{useState} from 'react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import type {LocaleCode} from '@/data/internationalSeo';
import { Send, CheckCircle2, Zap, ShieldCheck, Heart, Sparkles, ArrowRight, Lock, EyeOff, Scale, CheckSquare, AlertTriangle } from 'lucide-react';

type Copy={about:string[];contact:string[];privacy:string[];terms:string[]};
const COPY:Record<LocaleCode,Copy>={
en:{about:['About Toolployee','Making Everyday Digital Tasks','Effortless.','A free utility hub for PDF, image, developer, text, conversion, calculator, finance, compiler, and YouTube tasks.','Explore All Free Tools','Our Journey','Built to Solve Real-World Daily Inconveniences','Toolployee brings useful digital tools together in one clean interface. Simple tasks stay simple without heavy software or required accounts.','Core Values','What Guides Toolployee','Fast & Accessible|Privacy First|Free for Everyone|Community Feedback'],contact:['Contact & Support','How can we','help you?','Have a tool request, sandbox issue, or compiler suggestion? Send it to our technical team.','Strict Privacy & Zero Spam','Your email is used for support responses and not for marketing.','Message Transmitted!','Thank you. Our team reviews submissions within 24–48 hours.','Send Another Message','Name','Email','Your Message','Your Name','Write your feedback, bug report, or utility request here...','Send Message','Transmitting...','Unable to send your message right now.'],privacy:['Trust & Security','Privacy Policy','Effective: September 2026','1. Processing Architecture','Many PDF, image, text, converter, and calculator operations run in your browser. Compiler tools may send code to the configured runtime.','2. Data Retention & Tab Termination','We do not maintain user accounts or personal profiles. Browser-local data may remain according to normal browser behavior.','3. Third-Party Analytics & Cookies','We may use non-intrusive analytics and contextual advertising such as Google AdSense to keep the platform free.'],terms:['Legal Terms','Terms of Service','Last Updated: September 2026','1. Acceptance & Availability','By using Toolployee, you agree to these Terms. Utilities are provided “as is” without a guarantee of continuous availability.','2. Commercial Rights & Ownership','You retain ownership of assets generated or compiled through our tools and may use them subject to applicable law.','3. Financial & Informational Disclaimer','Calculators provide mathematical estimates only and are not formal investment advice or banking commitments.']},
pt:{about:['Sobre o Toolployee','Tornando as tarefas digitais do dia a dia','mais fáceis.','Um hub gratuito para PDF, imagens, desenvolvimento, texto, conversão, cálculos, finanças, compiladores e YouTube.','Explorar todas as ferramentas grátis','Nossa jornada','Criado para resolver inconvenientes reais do dia a dia','O Toolployee reúne ferramentas úteis em uma interface limpa. Tarefas simples não precisam de software pesado ou conta obrigatória.','Valores principais','O que orienta o Toolployee','Rápido e acessível|Privacidade em primeiro lugar|Grátis para todos|Feedback da comunidade'],contact:['Contato e suporte','Como podemos','ajudar você?','Tem um pedido de ferramenta, problema no sandbox ou sugestão de compilador? Envie para nossa equipe técnica.','Privacidade rigorosa e zero spam','Seu e-mail é usado para suporte e não para marketing.','Mensagem enviada!','Obrigado. Nossa equipe analisa os envios em 24–48 horas.','Enviar outra mensagem','Nome','E-mail','Sua mensagem','Seu nome','Escreva seu feedback, bug ou pedido de ferramenta...','Enviar mensagem','Enviando...','Não foi possível enviar sua mensagem agora.'],privacy:['Confiança e segurança','Política de privacidade','Vigente: setembro de 2026','1. Arquitetura de processamento','Muitas operações funcionam no navegador. Compiladores podem enviar código ao runtime configurado.','2. Retenção de dados e encerramento da aba','Não mantemos contas ou perfis pessoais. Dados locais podem permanecer conforme o comportamento normal do navegador.','3. Análises de terceiros e cookies','Podemos usar análises não intrusivas e publicidade contextual, como Google AdSense, para manter a plataforma gratuita.'],terms:['Termos legais','Termos de serviço','Última atualização: setembro de 2026','1. Aceitação e disponibilidade','Ao usar o Toolployee, você concorda com estes Termos. As ferramentas são fornecidas “como estão”.','2. Direitos comerciais e propriedade','Você mantém a propriedade dos ativos gerados ou compilados e pode usá-los conforme a lei aplicável.','3. Aviso financeiro e informativo','As calculadoras fornecem apenas estimativas matemáticas e não constituem aconselhamento de investimento ou compromisso bancário.']},
es:{about:['Acerca de Toolployee','Haciendo que las tareas digitales diarias sean','más fáciles.','Un centro gratuito para PDF, imágenes, desarrollo, texto, conversión, cálculos, finanzas, compiladores y YouTube.','Explorar todas las herramientas gratis','Nuestro recorrido','Creado para resolver inconvenientes reales del día a día','Toolployee reúne herramientas útiles en una interfaz limpia. Las tareas simples no necesitan software pesado ni una cuenta obligatoria.','Valores principales','Lo que guía a Toolployee','Rápido y accesible|Privacidad primero|Gratis para todos|Comentarios de la comunidad'],contact:['Contacto y soporte','¿Cómo podemos','ayudarte?','¿Tienes una solicitud, problema de sandbox o sugerencia de compilador? Envíala a nuestro equipo técnico.','Privacidad estricta y cero spam','Tu correo se usa para soporte y no para marketing.','¡Mensaje enviado!','Gracias. Nuestro equipo revisa los envíos en 24–48 horas.','Enviar otro mensaje','Nombre','Correo electrónico','Tu mensaje','Tu nombre','Escribe aquí tus comentarios, error o solicitud...','Enviar mensaje','Enviando...','No se pudo enviar el mensaje ahora.'],privacy:['Confianza y seguridad','Política de privacidad','Vigente: septiembre de 2026','1. Arquitectura de procesamiento','Muchas operaciones funcionan en el navegador. Los compiladores pueden enviar código al runtime configurado.','2. Retención de datos y cierre de pestañas','No mantenemos cuentas ni perfiles personales. Los datos locales pueden permanecer según el comportamiento normal del navegador.','3. Analítica de terceros y cookies','Podemos usar analítica no intrusiva y publicidad contextual como Google AdSense para mantener la plataforma gratuita.'],terms:['Términos legales','Términos del servicio','Última actualización: septiembre de 2026','1. Aceptación y disponibilidad','Al usar Toolployee, aceptas estos Términos. Las herramientas se ofrecen “tal cual”.','2. Derechos comerciales y propiedad','Conservas la propiedad de los activos generados o compilados y puedes usarlos según la ley.','3. Aviso financiero e informativo','Las calculadoras solo proporcionan estimaciones matemáticas y no constituyen asesoramiento de inversión.']},
de:{about:['Über Toolployee','Alltägliche digitale Aufgaben','einfacher machen.','Ein kostenloser Hub für PDF, Bilder, Entwicklung, Text, Konvertierung, Rechner, Finanzen, Compiler und YouTube.','Alle kostenlosen Tools entdecken','Unsere Reise','Entwickelt, um echte Alltagsprobleme zu lösen','Toolployee bündelt nützliche Werkzeuge in einer klaren Oberfläche. Einfache Aufgaben brauchen keine schwere Software oder ein Pflichtkonto.','Grundwerte','Was Toolployee leitet','Schnell und zugänglich|Datenschutz zuerst|Kostenlos für alle|Community-Feedback'],contact:['Kontakt und Support','Wie können wir','dir helfen?','Tool-Wunsch, Sandbox-Problem oder Compiler-Vorschlag? Sende ihn an unser Technikteam.','Strenger Datenschutz und kein Spam','Deine E-Mail wird für Support und nicht für Marketing verwendet.','Nachricht gesendet!','Danke. Unser Team prüft Einsendungen innerhalb von 24–48 Stunden.','Weitere Nachricht senden','Name','E-Mail','Deine Nachricht','Dein Name','Schreibe Feedback, Fehlerbericht oder Tool-Wunsch...','Nachricht senden','Wird gesendet...','Die Nachricht konnte gerade nicht gesendet werden.'],privacy:['Vertrauen und Sicherheit','Datenschutzerklärung','Gültig ab: September 2026','1. Verarbeitungsarchitektur','Viele Funktionen laufen im Browser. Compiler können Code an das konfigurierte Runtime senden.','2. Datenspeicherung und Tab-Ende','Wir führen keine Benutzerkonten oder persönlichen Profile. Lokale Daten können gemäß normalem Browserverhalten erhalten bleiben.','3. Drittanbieter-Analysen und Cookies','Wir können nicht aufdringliche Analysen und kontextbezogene Werbung wie Google AdSense verwenden.'],terms:['Rechtliche Hinweise','Nutzungsbedingungen','Zuletzt aktualisiert: September 2026','1. Zustimmung und Verfügbarkeit','Durch die Nutzung von Toolployee stimmst du diesen Bedingungen zu. Tools werden „wie besehen“ bereitgestellt.','2. Kommerzielle Rechte und Eigentum','Du behältst das Eigentum an erzeugten oder kompilierten Inhalten und kannst sie nach geltendem Recht nutzen.','3. Finanz- und Informationshinweis','Rechner liefern mathematische Schätzungen und sind keine formelle Anlageberatung.']},
fr:{about:['À propos de Toolployee','Rendre les tâches numériques quotidiennes','plus simples.','Un hub gratuit pour PDF, images, développement, texte, conversion, calcul, finance, compilation et YouTube.','Découvrir tous les outils gratuits','Notre parcours','Conçu pour les problèmes réels du quotidien','Toolployee réunit des outils utiles dans une interface claire. Les tâches simples ne nécessitent ni logiciel lourd ni compte obligatoire.','Valeurs clés','Ce qui guide Toolployee','Rapide et accessible|Confidentialité d’abord|Gratuit pour tous|Retours de la communauté'],contact:['Contact et assistance','Comment pouvons-nous','vous aider ?','Demande d’outil, problème de sandbox ou suggestion de compilateur ? Envoyez-la à notre équipe technique.','Confidentialité stricte et zéro spam','Votre e-mail sert au support et non au marketing.','Message envoyé !','Merci. Notre équipe examine les envois sous 24 à 48 heures.','Envoyer un autre message','Nom','E-mail','Votre message','Votre nom','Écrivez vos commentaires, bug ou demande...','Envoyer le message','Envoi...','Impossible d’envoyer le message pour le moment.'],privacy:['Confiance et sécurité','Politique de confidentialité','En vigueur : septembre 2026','1. Architecture du traitement','De nombreuses opérations fonctionnent dans le navigateur. Les compilateurs peuvent envoyer du code au runtime configuré.','2. Conservation des données et fermeture des onglets','Nous ne conservons pas de comptes ou profils personnels. Les données locales peuvent rester selon le navigateur.','3. Analyses tierces et cookies','Nous pouvons utiliser une télémétrie non intrusive et des publicités contextuelles comme Google AdSense.'],terms:['Mentions légales','Conditions d’utilisation','Dernière mise à jour : septembre 2026','1. Acceptation et disponibilité','En utilisant Toolployee, vous acceptez ces conditions. Les outils sont fournis « tels quels ».','2. Droits commerciaux et propriété','Vous conservez la propriété des éléments générés ou compilés et pouvez les utiliser selon la loi.','3. Avertissement financier et informatif','Les calculatrices fournissent des estimations mathématiques et ne constituent pas un conseil d’investissement.']},
it:{about:['Informazioni su Toolployee','Rendere le attività digitali quotidiane','più semplici.','Un hub gratuito per PDF, immagini, sviluppo, testo, conversione, calcolo, finanza, compilazione e YouTube.','Esplora tutti gli strumenti gratuiti','Il nostro percorso','Creato per risolvere i problemi quotidiani','Toolployee riunisce strumenti utili in un’interfaccia pulita. Le attività semplici non richiedono software pesante o account obbligatori.','Valori fondamentali','Cosa guida Toolployee','Veloce e accessibile|Privacy prima di tutto|Gratis per tutti|Feedback della community'],contact:['Contatti e assistenza','Come possiamo','aiutarti?','Hai una richiesta, un problema nel sandbox o una proposta per un compilatore? Inviala al team tecnico.','Privacy rigorosa e zero spam','La tua e-mail serve al supporto e non al marketing.','Messaggio inviato!','Grazie. Il team esamina gli invii entro 24–48 ore.','Invia un altro messaggio','Nome','E-mail','Il tuo messaggio','Il tuo nome','Scrivi feedback, bug o richiesta di strumento...','Invia messaggio','Invio...','Impossibile inviare il messaggio ora.'],privacy:['Fiducia e sicurezza','Informativa sulla privacy','In vigore: settembre 2026','1. Architettura di elaborazione','Molte operazioni funzionano nel browser. I compiler possono inviare codice al runtime configurato.','2. Conservazione dei dati e chiusura delle schede','Non manteniamo account o profili personali. I dati locali possono restare secondo il comportamento del browser.','3. Analisi di terze parti e cookie','Possiamo usare analisi non invasive e pubblicità contestuale come Google AdSense.'],terms:['Termini legali','Termini di servizio','Ultimo aggiornamento: settembre 2026','1. Accettazione e disponibilità','Usando Toolployee, accetti questi Termini. Gli strumenti sono forniti “così come sono”.','2. Diritti commerciali e proprietà','Mantieni la proprietà dei contenuti generati o compilati e puoi usarli secondo la legge.','3. Avvertenza finanziaria e informativa','I calcolatori forniscono stime matematiche e non costituiscono consulenza finanziaria.']},
ja:{about:['Toolployeeについて','日常のデジタル作業を','もっと簡単に。','PDF、画像、開発、テキスト、変換、計算、金融、コンパイラ、YouTube向けの無料ツールハブです。','すべての無料ツールを見る','私たちの歩み','日常の不便を解決するために','Toolployeeは便利なデジタルツールを分かりやすい画面にまとめます。簡単な作業に重いソフトや必須アカウントは必要ありません。','コアバリュー','Toolployeeを支えるもの','高速で使いやすい|プライバシー第一|すべての人に無料|コミュニティの声'],contact:['お問い合わせ・サポート','どのように','お手伝いできますか？','ツールの要望、サンドボックスの問題、新しいコンパイラの提案を技術チームへ送ってください。','厳格なプライバシーとスパムゼロ','メールはサポートへの返信にのみ使用します。','メッセージを送信しました！','ありがとうございます。24～48時間以内に確認します。','別のメッセージを送る','名前','メール','メッセージ','お名前','フィードバックやバグ、ツールの要望を入力してください…','送信','送信中…','現在メッセージを送信できません。'],privacy:['信頼とセキュリティ','プライバシーポリシー','施行日：2026年9月','1. 処理アーキテクチャ','PDF、画像、テキスト、変換、計算の多くはブラウザで処理されます。コンパイラは実行ランタイムへコードを送信できます。','2. データ保持とタブ終了','ユーザーアカウントや個人プロフィールは保持しません。ローカルデータは残る場合があります。','3. 第三者分析とCookie','無料提供のため、Google AdSenseなどの分析・広告サービスを利用する場合があります。'],terms:['法的事項','利用規約','最終更新：2026年9月','1. 同意と利用可能性','Toolployeeを利用すると本規約に同意したものとします。ツールは「現状有姿」で提供されます。','2. 商用利用権と所有権','ツールで生成またはコンパイルした成果物の所有権は利用者にあります。','3. 金融・情報に関する免責','計算ツールは数学的な推定値のみを提供し、正式な投資助言ではありません。']},
ko:{about:['Toolployee 소개','일상적인 디지털 작업을','더 쉽게.','PDF, 이미지, 개발, 텍스트, 변환, 계산, 금융, 컴파일러 및 YouTube를 위한 무료 도구 허브입니다.','모든 무료 도구 보기','우리의 여정','실제 일상의 불편을 해결하기 위해','Toolployee는 유용한 디지털 도구를 하나의 깔끔한 화면에 모읍니다. 간단한 작업에는 무거운 소프트웨어나 필수 계정이 필요하지 않습니다.','핵심 가치','Toolployee를 이끄는 원칙','빠르고 접근하기 쉬움|개인정보 보호 우선|모두에게 무료|커뮤니티 피드백'],contact:['문의 및 지원','어떻게','도와드릴까요?','도구 요청, 샌드박스 문제 또는 새 컴파일러 제안을 기술팀에 보내주세요.','엄격한 개인정보 보호와 스팸 없음','이메일은 지원 답변에만 사용합니다.','메시지가 전송되었습니다!','감사합니다. 24~48시간 내에 검토합니다.','다른 메시지 보내기','이름','이메일','메시지','이름','피드백, 버그 또는 도구 요청을 입력하세요...','메시지 보내기','전송 중...','지금은 메시지를 보낼 수 없습니다.'],privacy:['신뢰 및 보안','개인정보처리방침','시행: 2026년 9월','1. 처리 구조','많은 작업이 브라우저에서 처리됩니다. 컴파일러는 설정된 실행 런타임으로 코드를 보낼 수 있습니다.','2. 데이터 보관 및 탭 종료','사용자 계정이나 개인 프로필을 유지하지 않습니다. 로컬 데이터는 남을 수 있습니다.','3. 제3자 분석 및 쿠키','무료 운영을 위해 Google AdSense 같은 분석 및 광고 서비스를 사용할 수 있습니다.'],terms:['법적 약관','서비스 약관','최종 업데이트: 2026년 9월','1. 동의 및 이용 가능성','Toolployee를 사용하면 약관에 동의합니다. 도구는 “있는 그대로” 제공됩니다.','2. 상업적 권리 및 소유권','도구로 생성하거나 컴파일한 결과물의 소유권은 사용자에게 있습니다.','3. 금융 및 정보 면책','계산기는 수학적 추정치만 제공하며 공식 투자 자문이 아닙니다.']},
zh:{about:['关于 Toolployee','让日常数字任务','更加轻松。','一个免费的工具中心，适用于 PDF、图片、开发、文本、转换、计算、金融、编译器和 YouTube。','探索全部免费工具','我们的历程','为解决真实的日常不便而打造','Toolployee把实用的数字工具集中在一个简洁界面中。简单任务无需大型软件或强制账户。','核心价值','Toolployee的理念','快速易用|隐私优先|人人免费|社区反馈'],contact:['联系与支持','我们可以如何','帮助你？','有工具需求、沙盒问题或新的编译器建议？请发送给技术团队。','严格隐私，零垃圾邮件','你的邮箱仅用于支持回复，不用于营销。','消息已发送！','谢谢。我们会在24–48小时内查看。','发送另一条消息','姓名','电子邮件','你的消息','你的姓名','写下反馈、错误报告或工具需求...','发送消息','发送中...','目前无法发送消息。'],privacy:['信任与安全','隐私政策','生效时间：2026年9月','1. 处理架构','许多操作在浏览器中运行。编译器可能向配置的执行运行时发送代码。','2. 数据保留与标签页关闭','我们不维护用户账户或个人资料。本地数据可能保留。','3. 第三方分析与 Cookie','为保持免费，我们可能使用 Google AdSense 等分析和上下文广告服务。'],terms:['法律条款','服务条款','最后更新：2026年9月','1. 接受与可用性','使用 Toolployee 即表示同意这些条款。工具按“现状”提供。','2. 商业权利与所有权','通过工具生成或编译的成果归用户所有，并可依法使用。','3. 财务与信息免责声明','计算器仅提供数学估算，不构成正式投资建议。']},
ru:{about:['О Toolployee','Сделаем повседневные цифровые задачи','проще.','Бесплатный набор инструментов для PDF, изображений, разработки, текста, конвертации, расчётов, финансов, компиляторов и YouTube.','Открыть все бесплатные инструменты','Наш путь','Создано для решения реальных задач','Toolployee объединяет полезные цифровые инструменты в одном интерфейсе. Для простых задач не нужны тяжёлые программы или обязательный аккаунт.','Основные ценности','Что определяет Toolployee','Быстро и доступно|Конфиденциальность прежде всего|Бесплатно для всех|Отзывы сообщества'],contact:['Контакты и поддержка','Как мы можем','вам помочь?','Есть запрос на инструмент, проблема с sandbox или предложение компилятора? Отправьте его технической команде.','Строгая конфиденциальность и ноль спама','E-mail используется для поддержки, а не для маркетинга.','Сообщение отправлено!','Спасибо. Команда проверит обращение в течение 24–48 часов.','Отправить ещё сообщение','Имя','Электронная почта','Ваше сообщение','Ваше имя','Напишите отзыв, ошибку или запрос...','Отправить сообщение','Отправка...','Сейчас сообщение отправить не удалось.'],privacy:['Доверие и безопасность','Политика конфиденциальности','Действует: сентябрь 2026','1. Архитектура обработки','Многие операции выполняются в браузере. Компиляторы могут отправлять код в настроенную среду.','2. Хранение данных и закрытие вкладки','Мы не создаём аккаунты или личные профили. Локальные данные могут сохраняться.','3. Сторонняя аналитика и cookie','Для бесплатной работы мы можем использовать Google AdSense и ненавязчивую аналитику.'],terms:['Юридические условия','Условия использования','Последнее обновление: сентябрь 2026','1. Принятие и доступность','Используя Toolployee, вы принимаете условия. Инструменты предоставляются «как есть».','2. Коммерческие права и собственность','Вы сохраняете права на созданные или скомпилированные материалы и можете использовать их по закону.','3. Финансовая и информационная оговорка','Калькуляторы дают математические оценки и не являются инвестиционной консультацией.']},
ar:{about:['حول Toolployee','نجعل المهام الرقمية اليومية','أسهل.','مجموعة مجانية لأدوات PDF والصور والتطوير والنصوص والتحويل والحسابات والتمويل والمترجمات وYouTube.','استكشف جميع الأدوات المجانية','رحلتنا','صُمم لحل مشكلات الحياة اليومية','يجمع Toolployee الأدوات الرقمية المفيدة في واجهة واضحة. المهام البسيطة لا تحتاج إلى برامج ثقيلة أو حساب إلزامي.','القيم الأساسية','ما الذي يوجه Toolployee','سريع وسهل الوصول|الخصوصية أولاً|مجاني للجميع|ملاحظات المجتمع'],contact:['الاتصال والدعم','كيف يمكننا','مساعدتك؟','هل لديك طلب أداة أو مشكلة في sandbox أو اقتراح لمترجم؟ أرسله إلى فريقنا التقني.','خصوصية صارمة وبدون رسائل مزعجة','يُستخدم بريدك للرد على الدعم وليس للتسويق.','تم إرسال الرسالة!','شكراً. سيراجع فريقنا الرسالة خلال 24–48 ساعة.','إرسال رسالة أخرى','الاسم','البريد الإلكتروني','رسالتك','اسمك','اكتب ملاحظاتك أو تقرير الخطأ أو طلب الأداة...','إرسال الرسالة','جارٍ الإرسال...','تعذر إرسال الرسالة الآن.'],privacy:['الثقة والأمان','سياسة الخصوصية','سارية: سبتمبر 2026','1. بنية المعالجة','تعمل العديد من العمليات داخل المتصفح. قد ترسل المترجمات الكود إلى بيئة التنفيذ.','2. الاحتفاظ بالبيانات وإغلاق علامة التبويب','لا نحتفظ بحسابات أو ملفات شخصية. قد تبقى البيانات المحلية.','3. التحليلات وملفات تعريف الارتباط','قد نستخدم Google AdSense وتحليلات غير متطفلة للحفاظ على المنصة مجانية.'],terms:['الشروط القانونية','شروط الخدمة','آخر تحديث: سبتمبر 2026','1. القبول والتوافر','باستخدام Toolployee توافق على الشروط. تُقدم الأدوات «كما هي».','2. الحقوق التجارية والملكية','تحتفظ بملكية الأصول التي تنشئها أو تجمعها عبر أدواتنا ويمكنك استخدامها وفق القانون.','3. إخلاء المسؤولية المالية والمعلوماتية','توفر الآلات الحاسبة تقديرات رياضية فقط ولا تشكل استشارة استثمارية.']},
hi:{about:['Toolployee के बारे में','रोज़मर्रा के डिजिटल कामों को','आसान बनाना।','PDF, इमेज, डेवलपमेंट, टेक्स्ट, कन्वर्ज़न, कैलकुलेशन, फाइनेंस, कंपाइलर और YouTube के लिए मुफ्त टूल हब।','सभी मुफ्त टूल्स देखें','हमारी यात्रा','रोज़मर्रा की असली परेशानियों को हल करने के लिए','Toolployee उपयोगी डिजिटल टूल्स को एक साफ इंटरफेस में लाता है। आसान कामों के लिए भारी सॉफ्टवेयर या अनिवार्य अकाउंट की जरूरत नहीं है।','मुख्य मूल्य','Toolployee को क्या दिशा देता है','तेज़ और आसान|प्राइवेसी पहले|सभी के लिए मुफ्त|कम्युनिटी फीडबैक'],contact:['संपर्क और सपोर्ट','हम आपकी','कैसे मदद कर सकते हैं?','टूल रिक्वेस्ट, sandbox समस्या या नए compiler का सुझाव है? इसे तकनीकी टीम को भेजें।','सख्त प्राइवेसी और जीरो स्पैम','आपका ईमेल सपोर्ट जवाबों के लिए है, मार्केटिंग के लिए नहीं।','मैसेज भेज दिया गया!','धन्यवाद। हमारी टीम 24–48 घंटे में इसे देखेगी।','दूसरा मैसेज भेजें','नाम','ईमेल','आपका मैसेज','आपका नाम','फीडबैक, बग रिपोर्ट या टूल रिक्वेस्ट लिखें...','मैसेज भेजें','भेज रहे हैं...','अभी मैसेज भेजा नहीं जा सका।'],privacy:['विश्वास और सुरक्षा','प्राइवेसी पॉलिसी','प्रभावी: सितंबर 2026','1. प्रोसेसिंग आर्किटेक्चर','कई PDF, इमेज, टेक्स्ट और कैलकुलेटर काम ब्राउज़र में चलते हैं। Compiler tools configured runtime को code भेज सकते हैं।','2. डेटा रिटेंशन और टैब बंद करना','हम user accounts या personal profiles नहीं रखते। Local data सामान्य browser behavior के अनुसार रह सकता है।','3. थर्ड-पार्टी Analytics और Cookies','प्लेटफॉर्म को मुफ्त रखने के लिए Google AdSense जैसी सेवाओं और analytics का उपयोग हो सकता है।'],terms:['कानूनी शर्तें','सेवा की शर्तें','अंतिम अपडेट: सितंबर 2026','1. स्वीकृति और उपलब्धता','Toolployee का उपयोग करके आप इन शर्तों से सहमत हैं। टूल्स “जैसे हैं” आधार पर दिए जाते हैं।','2. Commercial Rights और Ownership','हमारे टूल्स से बनाए या compiled assets का ownership आपका रहता है और लागू कानून के अनुसार उपयोग किया जा सकता है।','3. Financial और Informational Disclaimer','Calculators केवल mathematical estimates देते हैं और formal investment advice नहीं हैं।']}
};

const ABOUT_STORY: Record<LocaleCode, [string,string,string]> = {
  en:[
    'Toolployee started from a simple frustration: whenever you need to quickly resize an image, test a query, calculate interest, or grab a thumbnail, modern search results lead to bloated websites covered in paywalls, forced email registrations, or daily limits.',
    'We believed simple tasks should remain simple. You should not need to download heavy desktop software or hand over personal data just to format text or convert an image.',
    'Our vision is straightforward: bring together high-utility everyday digital tools into a clean, modern interface where anyone can get their job done instantly and get back to what matters.'
  ],
  pt:[
    'O Toolployee nasceu de uma frustração simples: quando você precisa redimensionar uma imagem, testar uma consulta, calcular juros ou obter uma miniatura rapidamente, muitos resultados levam a sites pesados com paywalls, cadastros obrigatórios ou limites diários.',
    'Acreditamos que tarefas simples devem continuar simples. Você não deveria precisar instalar software pesado ou fornecer dados pessoais apenas para formatar texto ou converter uma imagem.',
    'Nossa visão é direta: reunir ferramentas digitais úteis do dia a dia em uma interface limpa e moderna, para que qualquer pessoa conclua sua tarefa rapidamente e volte ao que importa.'
  ],
  es:[
    'Toolployee nació de una frustración sencilla: cuando necesitas cambiar el tamaño de una imagen, probar una consulta, calcular intereses u obtener una miniatura, muchos resultados llevan a sitios pesados con pagos, registros obligatorios o límites diarios.',
    'Creemos que las tareas sencillas deben seguir siendo sencillas. No deberías instalar software pesado ni entregar datos personales solo para dar formato a un texto o convertir una imagen.',
    'Nuestra visión es clara: reunir herramientas digitales útiles en una interfaz limpia y moderna para que cualquiera pueda terminar su tarea rápidamente y volver a lo importante.'
  ],
  de:[
    'Toolployee entstand aus einer einfachen Frustration: Für Aufgaben wie Bilder skalieren, Abfragen testen, Zinsen berechnen oder Thumbnails abrufen führen Suchergebnisse oft zu überladenen Seiten mit Bezahlschranken, Pflichtregistrierungen oder Tageslimits.',
    'Wir glauben, dass einfache Aufgaben einfach bleiben sollten. Niemand sollte schwere Desktop-Software installieren oder persönliche Daten abgeben müssen, nur um Text zu formatieren oder ein Bild zu konvertieren.',
    'Unsere Vision ist klar: nützliche digitale Alltagswerkzeuge in einer modernen, übersichtlichen Oberfläche zu bündeln, damit Aufgaben schnell erledigt werden können.'
  ],
  fr:[
    'Toolployee est né d’une frustration simple : pour redimensionner une image, tester une requête, calculer des intérêts ou récupérer une miniature, les résultats de recherche mènent souvent vers des sites lourds avec paywalls, inscriptions obligatoires ou limites quotidiennes.',
    'Nous pensons que les tâches simples doivent rester simples. Il ne devrait pas être nécessaire d’installer un logiciel lourd ou de fournir des données personnelles pour formater un texte ou convertir une image.',
    'Notre vision est simple : réunir les outils numériques utiles du quotidien dans une interface moderne et claire, afin que chacun puisse terminer rapidement sa tâche et passer à l’essentiel.'
  ],
  it:[
    'Toolployee nasce da una frustrazione semplice: per ridimensionare un’immagine, testare una query, calcolare interessi o recuperare una miniatura, i risultati di ricerca portano spesso a siti pesanti con paywall, registrazioni obbligatorie o limiti giornalieri.',
    'Crediamo che le attività semplici debbano restare semplici. Non dovrebbe essere necessario installare software pesante o fornire dati personali solo per formattare testo o convertire un’immagine.',
    'La nostra visione è chiara: riunire strumenti digitali utili in un’interfaccia moderna e pulita, così chiunque può completare rapidamente il proprio lavoro e tornare a ciò che conta.'
  ],
  ja:[
    'Toolployeeは、画像のサイズ変更、クエリのテスト、利息計算、サムネイル取得などの簡単な作業でも、検索結果が広告や有料壁、必須登録、日次制限のある重いサイトに偏ることへの不便から始まりました。',
    '私たちは、簡単な作業は簡単なままであるべきだと考えています。テキスト整形や画像変換のためだけに重いソフトを入れたり、個人情報を渡したりする必要はありません。',
    '日常で役立つデジタルツールを、誰でもすぐ使えるクリーンで現代的な画面にまとめることが私たちの目標です。'
  ],
  ko:[
    'Toolployee는 이미지 크기 조정, 쿼리 테스트, 이자 계산, 썸네일 가져오기 같은 간단한 작업에서도 검색 결과가 무거운 사이트, 결제 장벽, 필수 가입, 일일 제한으로 이어지는 불편에서 시작했습니다.',
    '간단한 작업은 간단하게 남아야 한다고 생각합니다. 텍스트를 정리하거나 이미지를 변환하기 위해 무거운 데스크톱 소프트웨어를 설치하거나 개인정보를 제공할 필요가 없어야 합니다.',
    '일상에 유용한 디지털 도구를 깔끔하고 현대적인 인터페이스에 모아 누구나 필요한 일을 빠르게 끝낼 수 있도록 하는 것이 우리의 목표입니다.'
  ],
  zh:[
    'Toolployee源于一个简单的不便：当你需要快速调整图片、测试查询、计算利息或获取缩略图时，搜索结果常常把你带到包含付费墙、强制注册或每日限制的复杂网站。',
    '我们认为简单的任务就应该保持简单。仅仅为了格式化文本或转换图片，不应该必须安装大型桌面软件或提交个人信息。',
    '我们的愿景很直接：把日常真正有用的数字工具集中到简洁现代的界面中，让任何人都能快速完成任务并回到真正重要的事情上。'
  ],
  ru:[
    'Toolployee появился из простой проблемы: когда нужно быстро изменить размер изображения, проверить запрос, рассчитать проценты или получить миниатюру, результаты поиска часто ведут на перегруженные сайты с платными ограничениями, обязательной регистрацией или дневными лимитами.',
    'Мы считаем, что простые задачи должны оставаться простыми. Не нужно устанавливать тяжёлое ПО или передавать личные данные только ради форматирования текста или конвертации изображения.',
    'Наша цель проста: собрать полезные цифровые инструменты в чистом современном интерфейсе, чтобы любой пользователь мог быстро выполнить задачу и вернуться к важному.'
  ],
  ar:[
    'بدأ Toolployee من مشكلة بسيطة: عندما تحتاج سريعًا إلى تغيير حجم صورة أو اختبار استعلام أو حساب الفائدة أو الحصول على صورة مصغرة، تقود نتائج البحث كثيرًا إلى مواقع مزدحمة تتضمن جدران دفع أو تسجيلًا إلزاميًا أو حدودًا يومية.',
    'نؤمن بأن المهام البسيطة يجب أن تبقى بسيطة. لا ينبغي تثبيت برامج سطح مكتب ثقيلة أو تقديم بيانات شخصية لمجرد تنسيق نص أو تحويل صورة.',
    'رؤيتنا واضحة: جمع الأدوات الرقمية المفيدة للاستخدام اليومي في واجهة حديثة ونظيفة تساعد أي شخص على إنجاز المهمة بسرعة والعودة إلى ما يهم.'
  ],
  hi:[
    'Toolployee की शुरुआत एक सरल परेशानी से हुई: जब आपको जल्दी से इमेज का आकार बदलना हो, कोई क्वेरी टेस्ट करनी हो, ब्याज निकालना हो या थंबनेल पाना हो, तो खोज परिणाम अक्सर paywall, अनिवार्य registration या daily limits वाली भारी वेबसाइटों तक ले जाते हैं।',
    'हम मानते हैं कि आसान काम आसान ही रहने चाहिए। सिर्फ टेक्स्ट फॉर्मैट या इमेज कन्वर्ट करने के लिए भारी desktop software डाउनलोड करना या personal data देना जरूरी नहीं होना चाहिए।',
    'हमारा लक्ष्य सीधा है: रोज़मर्रा में काम आने वाले डिजिटल टूल्स को एक साफ और आधुनिक इंटरफेस में लाना, ताकि हर व्यक्ति अपना काम जल्दी पूरा कर सके और जरूरी चीजों पर वापस जा सके।'
  ]
};

const ABOUT_VALUE_DESCS: Record<LocaleCode, [string,string,string,string]> = {
  en:['Tools are designed for a clean, responsive experience on modern mobile and desktop browsers, with no installation required.','We do not require accounts for the tool suite. Browser-based processing is used where supported; tools that use an execution runtime are identified in their workflow.','Essential digital utilities should be open to all. Students, creators, and freelancers can access available tools without a required subscription tier.','We actively review tool suggestions and bug reports sent via our contact desk to continuously polish and expand the suite.'],
  pt:['As ferramentas são projetadas para uma experiência limpa e responsiva em navegadores modernos, sem instalação.','Não exigimos contas para o conjunto de ferramentas. O processamento no navegador é usado quando compatível; runtimes externos são indicados no fluxo.','Ferramentas digitais essenciais devem estar disponíveis para todos, sem assinatura obrigatória.','Analisamos sugestões e relatos de bugs enviados pelo contato para melhorar e ampliar o conjunto.'],
  es:['Las herramientas están diseñadas para una experiencia limpia y adaptable en navegadores modernos, sin instalación.','No exigimos cuentas. El procesamiento en el navegador se usa cuando es compatible y los runtimes externos se indican en el flujo.','Las herramientas digitales esenciales deben estar disponibles para todos, sin una suscripción obligatoria.','Revisamos sugerencias y errores enviados mediante contacto para mejorar y ampliar el conjunto.'],
  de:['Die Tools sind für eine klare, responsive Nutzung in modernen mobilen und Desktop-Browsern ohne Installation ausgelegt.','Für das Toolset ist kein Konto erforderlich. Browser-Verarbeitung wird genutzt, wo sie unterstützt wird; externe Laufzeiten werden im Ablauf gekennzeichnet.','Wichtige digitale Werkzeuge sollten allen offenstehen, ohne verpflichtendes Abonnement.','Wir prüfen Tool-Vorschläge und Fehlerberichte über den Kontakt, um das Angebot laufend zu verbessern.'],
  fr:['Les outils sont conçus pour une expérience claire et responsive dans les navigateurs modernes, sans installation.','Aucun compte n’est requis. Le traitement dans le navigateur est utilisé lorsqu’il est pris en charge et les runtimes externes sont indiqués.','Les outils numériques essentiels doivent être accessibles à tous, sans abonnement obligatoire.','Nous examinons les suggestions et rapports de bugs reçus afin d’améliorer et d’élargir la suite.'],
  it:['Gli strumenti sono progettati per un’esperienza pulita e responsive nei browser moderni, senza installazione.','Non è richiesto un account. L’elaborazione nel browser viene usata quando supportata e i runtime esterni sono indicati nel flusso.','Gli strumenti digitali essenziali dovrebbero essere disponibili a tutti senza abbonamento obbligatorio.','Esaminiamo suggerimenti e segnalazioni di bug per migliorare e ampliare continuamente la suite.'],
  ja:['ツールはインストール不要で、最新のモバイル・デスクトップブラウザで快適に使えるよう設計されています。','ツールの利用にアカウントは必要ありません。対応する処理はブラウザで行い、外部ランタイムを使う場合はフローで示します。','基本的なデジタルツールは、必須サブスクリプションなしで誰でも使えるべきだと考えています。','お問い合わせで届いた要望やバグ報告を確認し、ツール群を継続的に改善しています。'],
  ko:['도구는 설치 없이 최신 모바일 및 데스크톱 브라우저에서 깔끔하고 반응형으로 사용할 수 있도록 설계되었습니다.','도구 사용에 계정이 필요하지 않습니다. 지원되는 작업은 브라우저에서 처리하며 외부 런타임은 작업 흐름에 표시합니다.','필수 디지털 도구는 의무 구독 없이 누구나 사용할 수 있어야 합니다.','문의로 들어온 도구 제안과 버그 신고를 검토해 서비스를 계속 개선합니다.'],
  zh:['工具无需安装，并针对现代移动和桌面浏览器提供简洁、响应式的体验。','工具集合无需账户。支持的操作会在浏览器中处理，使用外部运行时的工具会在流程中说明。','基础数字工具应该对所有人开放，不应要求强制订阅。','我们会查看通过联系页面提交的工具建议和错误报告，持续改进和扩展工具集合。'],
  ru:['Инструменты рассчитаны на чистый адаптивный интерфейс в современных мобильных и настольных браузерах без установки.','Для набора инструментов не нужен аккаунт. Поддерживаемая обработка выполняется в браузере, а внешние среды отмечаются в рабочем процессе.','Необходимые цифровые инструменты должны быть доступны всем без обязательной подписки.','Мы рассматриваем предложения и сообщения об ошибках, чтобы постоянно улучшать и расширять набор.'],
  ar:['صُممت الأدوات لتقديم تجربة واضحة ومتجاوبة في المتصفحات الحديثة على الهاتف وسطح المكتب دون تثبيت.','لا نطلب حسابًا لاستخدام مجموعة الأدوات. تتم المعالجة داخل المتصفح عند دعمها، وتظهر بيئات التنفيذ الخارجية ضمن سير العمل.','ينبغي أن تكون الأدوات الرقمية الأساسية متاحة للجميع دون اشتراك إلزامي.','نراجع اقتراحات الأدوات وتقارير الأخطاء المرسلة عبر صفحة التواصل لتحسين المجموعة وتوسيعها.'],
  hi:['टूल्स को बिना इंस्टॉलेशन के आधुनिक मोबाइल और डेस्कटॉप ब्राउज़र में साफ और responsive अनुभव के लिए बनाया गया है।','टूल्स के लिए अकाउंट जरूरी नहीं है। जहाँ समर्थित है वहाँ प्रोसेसिंग ब्राउज़र में होती है और external runtime वाले टूल्स अपने workflow में इसे बताते हैं।','जरूरी डिजिटल टूल्स सभी के लिए उपलब्ध होने चाहिए, बिना अनिवार्य subscription के।','हम contact desk से मिली tool requests और bug reports की समीक्षा करके suite को लगातार बेहतर बनाते हैं।']
};

export default function LocalizedPlatformPage({locale,page}:{locale:LocaleCode;page:'about'|'contact'|'privacy'|'terms'}) {
  const c=COPY[locale] || COPY.en;
  const dir=locale==='ar'?'rtl':'ltr';
  const [formData,setFormData]=useState({name:'',email:'',message:''});
  const [isSubmitting,setIsSubmitting]=useState(false);
  const [isSuccess,setIsSuccess]=useState(false);
  const [submitError,setSubmitError]=useState('');

  if(page==='about'){
    const a=c.about;
    const metrics={
      en:['Free Utilities','Expanding continuously','No Paywalls','No hidden subscriptions','Sign-Ups Needed','Instant access to all tools','By Design','Files process right in your browser'],
      pt:['Utilitários gratuitos','Expansão contínua','Sem paywalls','Sem assinaturas ocultas','Cadastros necessários','Acesso instantâneo a todas as ferramentas','Por design','Os arquivos são processados no navegador'],
      es:['Herramientas gratuitas','Expansión continua','Sin paywalls','Sin suscripciones ocultas','Registros necesarios','Acceso instantáneo a todas las herramientas','Por diseño','Los archivos se procesan en tu navegador'],
      de:['Kostenlose Tools','Wird kontinuierlich erweitert','Keine Bezahlschranken','Keine versteckten Abos','Anmeldungen nötig','Sofortiger Zugriff auf alle Tools','Von Grund auf privat','Dateien werden im Browser verarbeitet'],
      fr:['Outils gratuits','En expansion continue','Sans paywall','Sans abonnements cachés','Inscription nécessaire','Accès instantané aux outils','Pensé ainsi','Les fichiers sont traités dans votre navigateur'],
      it:['Strumenti gratuiti','In continua espansione','Nessun paywall','Nessun abbonamento nascosto','Registrazioni necessarie','Accesso immediato a tutti gli strumenti','Progettato così','I file vengono elaborati nel browser'],
      ja:['無料ツール','継続的に拡大','ペイウォールなし','隠れた購読なし','登録不要','すべてのツールに即時アクセス','設計思想として','ファイルはブラウザ内で処理されます'],
      ko:['무료 도구','지속적으로 확장','페이월 없음','숨겨진 구독 없음','가입 불필요','모든 도구에 즉시 접근','설계상','파일은 브라우저에서 처리됩니다'],
      zh:['免费工具','持续扩展','无付费墙','无隐藏订阅','无需注册','即时使用所有工具','设计如此','文件直接在浏览器中处理'],
      ru:['Бесплатных инструментов','Постоянное расширение','Без платных стен','Без скрытых подписок','Регистрация не нужна','Мгновенный доступ ко всем инструментам','По задумке','Файлы обрабатываются в браузере'],
      ar:['أدوات مجانية','توسّع مستمر','بدون جدران دفع','بدون اشتراكات مخفية','لا حاجة للتسجيل','وصول فوري إلى جميع الأدوات','مصمم بهذه الطريقة','تُعالج الملفات داخل المتصفح'],
      hi:['मुफ्त टूल्स','लगातार विस्तार','कोई पेवॉल नहीं','कोई छिपी सदस्यता नहीं','साइन-अप की जरूरत नहीं','सभी टूल्स तक तुरंत पहुंच','डिज़ाइन के अनुसार','फाइलें ब्राउज़र में प्रोसेस होती हैं']
    }[locale] || ['Free Utilities','Expanding continuously','No Paywalls','No hidden subscriptions','Sign-Ups Needed','Instant access to all tools','By Design','Files process right in your browser'];
    return <div dir={dir} className="min-h-screen bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100 transition-colors flex flex-col justify-between">
      <div><Navbar/>
        <section className="mx-auto max-w-5xl px-4 pt-8 sm:pt-10 pb-8 text-center sm:px-6">
          <span className="text-[11px] font-bold uppercase tracking-widest text-violet-600 dark:text-violet-400">{a[0]}</span>
          <h1 className="mt-2 text-3xl sm:text-5xl lg:text-6xl font-black tracking-tight text-zinc-950 dark:text-white leading-[1.14]">{a[1]} <span className="bg-gradient-to-r from-violet-600 via-purple-600 to-indigo-600 dark:from-violet-400 dark:via-purple-400 dark:to-indigo-400 bg-clip-text text-transparent">{a[2]}</span></h1>
          <p className="mt-3 text-xs sm:text-sm md:text-base text-zinc-600 dark:text-zinc-400 max-w-2xl mx-auto leading-relaxed">{a[3]}</p>
          <div className="mt-6"><a href={'/'+locale+'#tools'} className="inline-flex items-center gap-2 rounded-2xl bg-violet-600 px-5 py-2.5 text-xs font-bold text-white shadow-md shadow-violet-500/20 hover:bg-violet-700 transition-all hover:scale-[1.02]"><span>{a[4]}</span><ArrowRight className="h-3.5 w-3.5"/></a></div>
        </section>
        <section className="border-y border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900/60 py-8">
          <div className="mx-auto max-w-5xl px-4 sm:px-6 grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            <div><p className="text-3xl sm:text-4xl font-black text-violet-600 dark:text-violet-400">87</p><p className="mt-1 text-xs font-bold text-zinc-800 dark:text-zinc-200">{metrics[0]}</p><p className="text-[11px] text-zinc-400">{metrics[1]}</p></div>
            <div><p className="text-3xl sm:text-4xl font-black text-violet-600 dark:text-violet-400">100%</p><p className="mt-1 text-xs font-bold text-zinc-800 dark:text-zinc-200">{metrics[2]}</p><p className="text-[11px] text-zinc-400">{metrics[3]}</p></div>
            <div><p className="text-3xl sm:text-4xl font-black text-violet-600 dark:text-violet-400">0</p><p className="mt-1 text-xs font-bold text-zinc-800 dark:text-zinc-200">{metrics[4]}</p><p className="text-[11px] text-zinc-400">{metrics[5]}</p></div>
            <div><p className="text-3xl sm:text-4xl font-black text-violet-600 dark:text-violet-400">{({en:"Private",pt:"Privado",es:"Privado",de:"Privat",fr:"Privé",it:"Privato",ja:"非公開",ko:"비공개",zh:"私密",ru:"Приватно",ar:"خاص",hi:"प्राइवेट"} as Record<string,string>)[locale]}</p><p className="mt-1 text-xs font-bold text-zinc-800 dark:text-zinc-200">{metrics[6]}</p><p className="text-[11px] text-zinc-400">{metrics[7]}</p></div>
          </div>
        </section>
        <main className="mx-auto max-w-4xl px-4 py-12 sm:px-6 space-y-12">
          <article className="space-y-3 text-center sm:text-left">
            <span className="text-xs font-bold uppercase tracking-wider text-violet-600 dark:text-violet-400">{a[5]}</span>
            <h2 className="text-2xl sm:text-3xl font-extrabold text-zinc-950 dark:text-white">{a[6]}</h2>
            <div className="space-y-4 text-xs sm:text-sm text-zinc-600 dark:text-zinc-300 leading-relaxed pt-1">{ABOUT_STORY[locale].map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div>
          </article>
          <section className="space-y-5">
            <div className="text-center sm:text-left"><span className="text-xs font-bold uppercase tracking-wider text-violet-600 dark:text-violet-400">{a[8]}</span><h2 className="text-2xl font-extrabold text-zinc-950 dark:text-white mt-1">{a[9]}</h2></div>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-5 shadow-sm space-y-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-100 dark:bg-violet-950/60 text-violet-600 dark:text-violet-400 mb-2"><Zap className="h-4 w-4"/></div><h3 className="text-sm font-bold text-zinc-900 dark:text-white">{a[10].split('|')[0]}</h3><p className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed">{ABOUT_VALUE_DESCS[locale][0]}</p></div>
              <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-5 shadow-sm space-y-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-emerald-100 dark:bg-emerald-950/60 text-emerald-600 dark:text-emerald-400 mb-2"><ShieldCheck className="h-4 w-4"/></div><h3 className="text-sm font-bold text-zinc-900 dark:text-white">{a[10].split('|')[1]}</h3><p className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed">{ABOUT_VALUE_DESCS[locale][1]}</p></div>
              <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-5 shadow-sm space-y-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-100 dark:bg-indigo-950/60 text-indigo-600 dark:text-indigo-400 mb-2"><Sparkles className="h-4 w-4"/></div><h3 className="text-sm font-bold text-zinc-900 dark:text-white">{a[10].split('|')[2]}</h3><p className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed">{ABOUT_VALUE_DESCS[locale][2]}</p></div>
              <div className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-5 shadow-sm space-y-2"><div className="flex h-9 w-9 items-center justify-center rounded-xl bg-pink-100 dark:bg-pink-950/60 text-pink-600 dark:text-pink-400 mb-2"><Heart className="h-4 w-4"/></div><h3 className="text-sm font-bold text-zinc-900 dark:text-white">{a[10].split('|')[3]}</h3><p className="text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed">{ABOUT_VALUE_DESCS[locale][3]}</p></div>
            </div>
          </section>
        </main>
      </div><Footer/>
    </div>;
  }

  if(page==='contact'){
    const a=c.contact;
    const handleSubmit=async(e:React.FormEvent)=>{e.preventDefault();setIsSubmitting(true);setSubmitError('');try{const res=await fetch('https://api.web3forms.com/submit',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify({access_key:'e87ad13c-a295-47b3-833e-ac4c1e3fd275',name:formData.name,email:formData.email,message:formData.message,from_name:'Toolployee Inquiries'})});const payload=await res.json().catch(()=>null);if(!res.ok||payload?.success===false)throw new Error(payload?.message||a[17]);setIsSuccess(true);setFormData({name:'',email:'',message:''});}catch(error){setSubmitError(error instanceof Error?error.message:a[17]);}finally{setIsSubmitting(false);}};
    return <div dir={dir} className="min-h-screen bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100 transition-colors flex flex-col justify-between">
      <div><Navbar/>
        <main className="mx-auto max-w-5xl px-4 py-16 sm:px-6"><div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start">
          <div className="lg:col-span-5 space-y-6"><span className="text-xs font-bold uppercase tracking-widest text-violet-600 dark:text-violet-400">{a[0]}</span><h1 className="text-4xl sm:text-5xl font-black tracking-tight text-zinc-950 dark:text-white leading-tight">{a[1]} <span className="bg-gradient-to-r from-violet-600 to-indigo-600 bg-clip-text text-transparent">{a[2]}</span></h1><p className="text-xs sm:text-sm text-zinc-600 dark:text-zinc-400 leading-relaxed">{a[3]}</p><div className="rounded-2xl border border-violet-100 dark:border-zinc-800 bg-violet-50/50 dark:bg-zinc-900/60 p-5 space-y-3"><div className="flex items-center gap-2 text-violet-700 dark:text-violet-400 font-bold text-xs"><Sparkles className="h-4 w-4"/><span>{a[4]}</span></div><p className="text-[11px] text-zinc-500 dark:text-zinc-400 leading-relaxed">{a[5]}</p></div></div>
          <div className="lg:col-span-7"><div className="rounded-3xl border border-zinc-200/90 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 sm:p-10 shadow-lg shadow-violet-500/5">
            {isSuccess?<div className="py-12 text-center space-y-4"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-emerald-50 dark:bg-emerald-950/50 text-emerald-600 border border-emerald-200 dark:border-emerald-800"><CheckCircle2 className="h-7 w-7"/></div><h3 className="text-lg font-bold text-zinc-900 dark:text-white">{a[6]}</h3><p className="text-xs text-zinc-500 max-w-sm mx-auto">{a[7]}</p><button onClick={()=>setIsSuccess(false)} className="rounded-xl bg-violet-600 px-5 py-2 text-xs font-bold text-white shadow hover:bg-violet-700">{a[8]}</button></div>:
            <form onSubmit={handleSubmit} className="space-y-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="space-y-1.5"><label className="text-xs font-bold text-zinc-700 dark:text-zinc-300">{a[9]}</label><input type="text" required placeholder={a[13]} value={formData.name} onChange={e=>setFormData({...formData,name:e.target.value})} className="w-full rounded-xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-800/60 px-4 py-3 text-xs text-zinc-900 dark:text-white focus:border-violet-600 focus:outline-none"/></div><div className="space-y-1.5"><label className="text-xs font-bold text-zinc-700 dark:text-zinc-300">{a[10]}</label><input type="email" required placeholder="example@domain.com" value={formData.email} onChange={e=>setFormData({...formData,email:e.target.value})} className="w-full rounded-xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-800/60 px-4 py-3 text-xs text-zinc-900 dark:text-white focus:border-violet-600 focus:outline-none"/></div></div><div className="space-y-1.5"><label className="text-xs font-bold text-zinc-700 dark:text-zinc-300">{a[11]}</label><textarea required rows={5} placeholder={a[12]} value={formData.message} onChange={e=>setFormData({...formData,message:e.target.value})} className="w-full rounded-xl border border-zinc-200 dark:border-zinc-800 bg-zinc-50 dark:bg-zinc-800/60 p-4 text-xs text-zinc-900 dark:text-white focus:border-violet-600 focus:outline-none resize-none"/></div>{submitError&&<p role="alert" className="text-xs text-red-600 dark:text-red-400">{submitError}</p>}<button type="submit" disabled={isSubmitting} className="w-full sm:w-auto inline-flex items-center justify-center gap-2 rounded-2xl bg-violet-600 px-8 py-3 text-xs font-bold text-white shadow-md shadow-violet-500/20 hover:bg-violet-700 transition-all disabled:opacity-60"><Send className="h-3.5 w-3.5"/><span>{isSubmitting?a[15]:a[14]}</span></button></form>}
          </div></div>
        </div></main>
      </div><Footer/>
    </div>;
  }

  const a=page==='privacy'?c.privacy:c.terms;
  const legalIcon=page==='privacy'?[Lock,EyeOff,ShieldCheck]:[Scale,CheckSquare,AlertTriangle];
  return <div dir={dir} className="min-h-screen bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100 transition-colors flex flex-col justify-between">
    <div><Navbar/><main className="mx-auto max-w-4xl px-4 py-16 sm:px-6"><div className="rounded-3xl border border-zinc-200/90 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-8 sm:p-12 shadow-sm space-y-8">
      <div className="border-b border-zinc-100 dark:border-zinc-800 pb-6"><span className="text-xs font-bold uppercase tracking-widest text-violet-600 dark:text-violet-400">{a[0]}</span><h1 className="mt-2 text-3xl sm:text-4xl font-black text-zinc-950 dark:text-white">{a[1]}</h1><p className="mt-1 text-xs text-zinc-500">{a[2]}</p></div>
      {[0,1,2].map((i)=>{const Icon=legalIcon[i];return <section key={i} className="space-y-3 text-xs sm:text-sm text-zinc-600 dark:text-zinc-300 leading-relaxed"><h2 className="text-base font-bold text-zinc-900 dark:text-white flex items-center gap-2"><Icon className="h-4 w-4 text-violet-600 dark:text-violet-400"/>{a[3+i*2]}</h2><p>{a[4+i*2]}</p></section>;})}
    </div></main></div><Footer/>
  </div>;
}
