'use client';

import React from 'react';
import { BarChart3, CheckCircle2, FileText, Image as ImageIcon, Code2, Type, ArrowRight, Calculator, Video, RefreshCw, ShieldCheck } from 'lucide-react';
import { ToolMeta } from '@/data/toolsRegistry';
import { getToolSeoContent, getLocalizedToolSeoContent } from '@/data/toolSeo';
import type { LocaleCode } from '@/data/internationalSeo';
import { getLocalizedToolName, getLocalizedCategoryLabel } from '@/data/internationalLocalization';

const SEO_LABELS: Record<LocaleCode, {
  guide:string; complete:string; why:string; how:string; useCases:string; best:string; limitations:string; quick:string; category:string; intent:string; access:string; browser:string; faq:string; source:string; transform:string; output:string; process:string; review:string; input:string;
}> = {
  en:{guide:'Complete tool guide',complete:'Everything you need to know about',why:'Why use',how:'How to use it',useCases:'Common use cases',best:'Best practices',limitations:'Important limitations',quick:'Quick reference',category:'Category',intent:'Primary intent',access:'Access',browser:'Browser-based',faq:'Frequently asked questions',source:'Source',transform:'Transform',output:'Output',process:'Process',review:'Review',input:'Input'},
  pt:{guide:'Guia completo da ferramenta',complete:'Tudo o que você precisa saber sobre',why:'Por que usar',how:'Como usar',useCases:'Casos de uso comuns',best:'Boas práticas',limitations:'Limitações importantes',quick:'Referência rápida',category:'Categoria',intent:'Intenção principal',access:'Acesso',browser:'Baseado no navegador',faq:'Perguntas frequentes',source:'Origem',transform:'Transformar',output:'Saída',process:'Processar',review:'Revisar',input:'Entrada'},
  es:{guide:'Guía completa de la herramienta',complete:'Todo lo que necesitas saber sobre',why:'Por qué usar',how:'Cómo usarla',useCases:'Casos de uso comunes',best:'Buenas prácticas',limitations:'Limitaciones importantes',quick:'Referencia rápida',category:'Categoría',intent:'Intención principal',access:'Acceso',browser:'Basado en navegador',faq:'Preguntas frecuentes',source:'Origen',transform:'Transformar',output:'Resultado',process:'Procesar',review:'Revisar',input:'Entrada'},
  de:{guide:'Vollständiger Tool-Leitfaden',complete:'Alles, was du über',why:'Warum verwenden',how:'So verwendest du es',useCases:'Häufige Anwendungsfälle',best:'Bewährte Vorgehensweisen',limitations:'Wichtige Einschränkungen',quick:'Schnellreferenz',category:'Kategorie',intent:'Hauptzweck',access:'Zugriff',browser:'Browserbasiert',faq:'Häufig gestellte Fragen',source:'Quelle',transform:'Umwandeln',output:'Ausgabe',process:'Verarbeiten',review:'Prüfen',input:'Eingabe'},
  fr:{guide:'Guide complet de l’outil',complete:'Tout ce que vous devez savoir sur',why:'Pourquoi utiliser',how:'Comment l’utiliser',useCases:'Cas d’utilisation courants',best:'Bonnes pratiques',limitations:'Limites importantes',quick:'Référence rapide',category:'Catégorie',intent:'Intention principale',access:'Accès',browser:'Dans le navigateur',faq:'Questions fréquentes',source:'Source',transform:'Transformer',output:'Résultat',process:'Traiter',review:'Vérifier',input:'Entrée'},
  it:{guide:'Guida completa dello strumento',complete:'Tutto ciò che devi sapere su',why:'Perché usarlo',how:'Come usarlo',useCases:'Casi d’uso comuni',best:'Buone pratiche',limitations:'Limitazioni importanti',quick:'Riferimento rapido',category:'Categoria',intent:'Intento principale',access:'Accesso',browser:'Basato sul browser',faq:'Domande frequenti',source:'Origine',transform:'Trasforma',output:'Risultato',process:'Elabora',review:'Verifica',input:'Input'},
  ja:{guide:'ツール完全ガイド',complete:'について知っておきたいこと',why:'利用する理由',how:'使い方',useCases:'主な用途',best:'ベストプラクティス',limitations:'重要な制限事項',quick:'クイックリファレンス',category:'カテゴリー',intent:'主な目的',access:'アクセス',browser:'ブラウザベース',faq:'よくある質問',source:'入力元',transform:'変換',output:'出力',process:'処理',review:'確認',input:'入力'},
  ko:{guide:'도구 전체 가이드',complete:'에 대해 알아야 할 모든 것',why:'사용하는 이유',how:'사용 방법',useCases:'일반적인 사용 사례',best:'권장 사용 방법',limitations:'중요한 제한 사항',quick:'빠른 참조',category:'카테고리',intent:'주요 용도',access:'접근',browser:'브라우저 기반',faq:'자주 묻는 질문',source:'원본',transform:'변환',output:'결과',process:'처리',review:'검토',input:'입력'},
  zh:{guide:'完整工具指南',complete:'关于你需要了解的一切',why:'为什么使用',how:'使用方法',useCases:'常见使用场景',best:'最佳实践',limitations:'重要限制',quick:'快速参考',category:'分类',intent:'主要用途',access:'访问方式',browser:'基于浏览器',faq:'常见问题',source:'来源',transform:'转换',output:'输出',process:'处理',review:'检查',input:'输入'},
  ru:{guide:'Полное руководство по инструменту',complete:'Всё, что нужно знать о',why:'Зачем использовать',how:'Как использовать',useCases:'Распространённые сценарии',best:'Рекомендации',limitations:'Важные ограничения',quick:'Краткая справка',category:'Категория',intent:'Основное назначение',access:'Доступ',browser:'Работает в браузере',faq:'Часто задаваемые вопросы',source:'Источник',transform:'Преобразование',output:'Результат',process:'Обработка',review:'Проверка',input:'Ввод'},
  ar:{guide:'دليل الأداة الكامل',complete:'كل ما تحتاج إلى معرفته عن',why:'لماذا تستخدم',how:'كيفية الاستخدام',useCases:'الاستخدامات الشائعة',best:'أفضل الممارسات',limitations:'قيود مهمة',quick:'مرجع سريع',category:'الفئة',intent:'الغرض الرئيسي',access:'الوصول',browser:'يعمل في المتصفح',faq:'الأسئلة الشائعة',source:'المصدر',transform:'تحويل',output:'الناتج',process:'معالجة',review:'مراجعة',input:'الإدخال'},
  hi:{guide:'टूल की पूरी गाइड',complete:'के बारे में आपको जो कुछ जानना चाहिए',why:'क्यों इस्तेमाल करें',how:'कैसे इस्तेमाल करें',useCases:'सामान्य उपयोग',best:'सर्वोत्तम तरीके',limitations:'महत्वपूर्ण सीमाएँ',quick:'त्वरित संदर्भ',category:'श्रेणी',intent:'मुख्य उद्देश्य',access:'एक्सेस',browser:'ब्राउज़र आधारित',faq:'अक्सर पूछे जाने वाले सवाल',source:'स्रोत',transform:'बदलें',output:'आउटपुट',process:'प्रोसेस',review:'जाँचें',input:'इनपुट'}
};

function VisualPanel({ tool, visual, labels }: { tool: ToolMeta; visual: ReturnType<typeof getToolSeoContent>['visual']; labels: typeof SEO_LABELS.en }) {
  const common = 'rounded-3xl border border-zinc-200/80 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-5 shadow-sm';
  if (visual === 'finance') return <div className={common}><div className="flex items-center gap-2 mb-4"><Calculator className="h-5 w-5 text-violet-600" /><h3 className="font-bold">{labels.process}</h3></div><div className="grid grid-cols-4 items-end gap-3 h-40">{[44,70,98,126].map((height,i)=><div key={i} className="flex h-full flex-col items-center justify-end gap-2"><div className="flex h-32 w-full items-end"><div className="w-full rounded-t-xl bg-violet-500/70 dark:bg-violet-400/70" style={{height}} /></div><span className="text-[10px] font-medium text-zinc-500">{labels.input} {String.fromCharCode(65+i)}</span></div>)}</div></div>;
  if (visual === 'formats') return <div className={common}><div className="flex items-center gap-2 mb-4"><ImageIcon className="h-5 w-5 text-violet-600" /><h3 className="font-bold">{labels.guide}</h3></div><div className="grid grid-cols-3 gap-2 text-xs font-semibold"><div className="rounded-2xl bg-zinc-50 dark:bg-zinc-950 border p-4 text-center">{labels.input}</div><ArrowRight className="h-4 w-4 self-center text-zinc-400" /><div className="rounded-2xl bg-zinc-50 dark:bg-zinc-950 border p-4 text-center">{labels.transform}</div><ArrowRight className="h-4 w-4 self-center text-zinc-400" /><div className="rounded-2xl bg-zinc-50 dark:bg-zinc-950 border p-4 text-center">{labels.output}</div></div></div>;
  if (visual === 'converter') return <div className={common}><div className="flex items-center gap-2 mb-4"><RefreshCw className="h-5 w-5 text-violet-600" /><h3 className="font-bold">{labels.process}</h3></div><div className="flex items-center justify-between gap-2"><span className="rounded-2xl bg-violet-50 dark:bg-violet-950/40 px-4 py-3 text-sm font-bold">{labels.source}</span><ArrowRight className="h-5 w-5 text-zinc-400" /><span className="rounded-2xl bg-emerald-50 dark:bg-emerald-950/40 px-4 py-3 text-sm font-bold">{labels.output}</span></div></div>;
  if (visual === 'code') return <div className={common}><div className="flex items-center gap-2 mb-4"><Code2 className="h-5 w-5 text-violet-600" /><h3 className="font-bold">{labels.process}</h3></div><div className="space-y-2 font-mono text-xs"><div className="rounded-xl bg-zinc-950 text-zinc-300 p-3">{labels.input} → {labels.review}</div><div className="rounded-xl bg-violet-950/50 text-violet-200 p-3">{labels.process} → {labels.transform} → {labels.review}</div><div className="rounded-xl bg-emerald-950/50 text-emerald-200 p-3">{labels.output} → {labels.review}</div></div></div>;
  if (visual === 'text') return <div className={common}><div className="flex items-center gap-2 mb-4"><Type className="h-5 w-5 text-violet-600" /><h3 className="font-bold">{labels.process}</h3></div><div className="grid grid-cols-3 gap-2 text-xs"><div className="rounded-2xl border p-4">{labels.input}</div><div className="rounded-2xl border p-4 bg-violet-50 dark:bg-violet-950/30">{labels.transform}</div><div className="rounded-2xl border p-4 bg-emerald-50 dark:bg-emerald-950/30">{labels.output}</div></div></div>;
  if (visual === 'youtube') return <div className={common}><div className="flex items-center gap-2 mb-4"><Video className="h-5 w-5 text-violet-600" /><h3 className="font-bold">{labels.process}</h3></div><div className="grid grid-cols-3 gap-2 text-xs"><div className="rounded-2xl border p-4">{labels.input}</div><div className="rounded-2xl border p-4 bg-violet-50 dark:bg-violet-950/30">{labels.transform}</div><div className="rounded-2xl border p-4 bg-emerald-50 dark:bg-emerald-950/30">{labels.output}</div></div></div>;
  return <div className={common}><div className="flex items-center gap-2 mb-4"><FileText className="h-5 w-5 text-violet-600" /><h3 className="font-bold">{labels.guide}</h3></div><div className="flex items-center justify-between gap-2"><div className="rounded-2xl border p-4 text-center text-xs font-semibold">{labels.source}</div><ArrowRight className="h-5 w-5 text-zinc-400" /><div className="rounded-2xl bg-violet-50 dark:bg-violet-950/30 border p-4 text-center text-xs font-semibold">{labels.process}</div><ArrowRight className="h-5 w-5 text-zinc-400" /><div className="rounded-2xl bg-emerald-50 dark:bg-emerald-950/30 border p-4 text-center text-xs font-semibold">{labels.review}</div></div></div>;
}

export default function ToolSeoContent({ tool, locale = 'en' }: { tool: ToolMeta; locale?: LocaleCode }) {
  const seo = getLocalizedToolSeoContent(tool, locale);
  const labels = SEO_LABELS[locale];
  const name = getLocalizedToolName(tool, locale);
  const category = getLocalizedCategoryLabel(tool.category, locale);
  return <section className="mt-14 border-t border-zinc-200/80 dark:border-zinc-800 pt-12">
    <div className="max-w-5xl mx-auto">
      <div className="mb-8">
        <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-violet-600 dark:text-violet-400">{labels.guide}</span>
        <h2 className="mt-2 text-2xl sm:text-3xl font-black tracking-tight">{labels.complete} {name}</h2>
        <p className="mt-3 text-sm sm:text-base leading-7 text-zinc-600 dark:text-zinc-400">{seo.intro}</p>
      </div>
      <div className="grid lg:grid-cols-[1.1fr_.9fr] gap-6">
        <div className="rounded-3xl border border-zinc-200/80 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 sm:p-7">
          <h3 className="text-lg font-bold">{labels.why} {name}?</h3>
          <p className="mt-3 text-sm leading-7 text-zinc-600 dark:text-zinc-400">{seo.why}</p>
          {seo.formula && <div className="mt-5 rounded-2xl bg-zinc-950 text-zinc-100 p-5"><div className="text-[10px] uppercase tracking-widest text-violet-300 font-bold mb-2">{labels.process}</div><p className="font-mono text-xs sm:text-sm leading-6">{seo.formula}</p></div>}
        </div>
        <VisualPanel tool={tool} visual={seo.visual} labels={labels} />
      </div>
      <div className="mt-6 grid md:grid-cols-2 gap-6">
        <div className="rounded-3xl border border-zinc-200/80 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6"><h3 className="text-lg font-bold">{labels.how}</h3><ol className="mt-4 space-y-4">{seo.steps.map((step,i)=><li key={step} className="flex gap-3"><span className="h-6 w-6 shrink-0 rounded-full bg-violet-100 dark:bg-violet-950/60 text-violet-700 dark:text-violet-300 text-xs font-bold flex items-center justify-center">{i+1}</span><p className="text-sm leading-6 text-zinc-600 dark:text-zinc-400">{step}</p></li>)}</ol></div>
        <div className="rounded-3xl border border-zinc-200/80 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6"><h3 className="text-lg font-bold">{labels.useCases}</h3><ul className="mt-4 space-y-3">{seo.useCases.map(x=><li key={x} className="flex gap-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400"><CheckCircle2 className="h-4 w-4 mt-1 shrink-0 text-emerald-500"/>{x}</li>)}</ul></div>
      </div>
      <div className="mt-6 grid md:grid-cols-2 gap-6">
        <div className="rounded-3xl border border-zinc-200/80 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6"><h3 className="text-lg font-bold">{labels.best}</h3><ul className="mt-4 space-y-3">{seo.tips.map(x=><li key={x} className="text-sm leading-6 text-zinc-600 dark:text-zinc-400">• {x}</li>)}</ul></div>
        <div className="rounded-3xl border border-amber-200/80 dark:border-amber-900/40 bg-amber-50/50 dark:bg-amber-950/10 p-6"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-amber-600"/><h3 className="text-lg font-bold">{labels.limitations}</h3></div><ul className="mt-4 space-y-3">{seo.limitations.map(x=><li key={x} className="text-sm leading-6 text-zinc-600 dark:text-zinc-400">• {x}</li>)}</ul></div>
      </div>
      <div className="mt-6 rounded-3xl border border-zinc-200/80 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-6 sm:p-7"><div className="flex items-center gap-2"><BarChart3 className="h-5 w-5 text-violet-600"/><h3 className="text-lg font-bold">{labels.quick}</h3></div><div className="mt-5 grid sm:grid-cols-3 gap-3"><div className="rounded-2xl bg-zinc-50 dark:bg-zinc-950 p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-400">{labels.category}</p><p className="mt-1 text-sm font-bold">{category}</p></div><div className="rounded-2xl bg-zinc-50 dark:bg-zinc-950 p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-400">{labels.intent}</p><p className="mt-1 text-sm font-bold">{name}</p></div><div className="rounded-2xl bg-zinc-50 dark:bg-zinc-950 p-4"><p className="text-[10px] uppercase tracking-wider text-zinc-400">{labels.access}</p><p className="mt-1 text-sm font-bold">{labels.browser}</p></div></div></div>
      <div className="mt-6"><h3 className="text-xl font-bold">{labels.faq}</h3><div className="mt-4 grid md:grid-cols-2 gap-4 items-stretch">{seo.faq.map(item=><details key={item.q} className="group flex h-full flex-col rounded-2xl border border-zinc-200/80 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-5"><summary className="cursor-pointer list-none pr-6 text-sm font-bold text-zinc-900 dark:text-white">{item.q}</summary><p className="mt-3 text-sm leading-6 text-zinc-600 dark:text-zinc-400">{item.a}</p></details>)}</div></div>
    </div>
  </section>;
}
