'use client';

import React, { useMemo, useState } from 'react';
import Link from 'next/link';
import {
  Search, FileText, Image as ImageIcon, Code, Calculator, Video, Type,
  ArrowRight, ShieldCheck, Zap, Lock, Cpu, MousePointerClick,
  Sparkles, ChevronDown, HelpCircle, Layers, ArrowLeftRight,
} from 'lucide-react';
import { TOOLS_REGISTRY, CATEGORIES, ToolMeta } from '@/data/toolsRegistry';
import { LOCALES, getLocale, localizedToolPath } from '@/data/internationalSeo';
import { getLocalizedToolName, getLocalizedUi, getLocalizedCategoryLabel } from '@/data/internationalLocalization';

type HomeCopy = {
  badge:string; title:string; accent:string; description:string; searchPlaceholder:string; search:string;
  popular:string; showing:string; utilities:string; explore:string;
  workflowBadge:string; workflowTitle:string; workflowDescription:string;
  selectTitle:string; selectDescription:string; processTitle:string; processDescription:string; exportTitle:string; exportDescription:string;
  privacyBadge:string; privacyTitle:string; privacyDescription:string;
  privacyOne:string; privacyOneDesc:string; privacyTwo:string; privacyTwoDesc:string; privacyThree:string; privacyThreeDesc:string;
  faqBadge:string; faqTitle:string; ctaTitle:string; ctaDescription:string; pick:string;
};

const COPY: Record<string, HomeCopy> = {
  pt:{badge:'Ferramentas online gratuitas',title:'Todas as ferramentas online gratuitas de que você precisa.',accent:'Você precisa.',description:'Ferramentas rápidas e seguras para PDF, imagens, código, conversões e cálculos, diretamente no navegador.',searchPlaceholder:'Pesquisar ferramentas (ex.: comprimir imagem, Python, SIP)...',search:'Pesquisar',popular:'Ferramentas populares',showing:'Mostrando',utilities:'ferramentas',explore:'Explorar todas as 87 ferramentas',workflowBadge:'Fluxo simples',workflowTitle:'Três etapas. Tudo no navegador.',workflowDescription:'Escolha uma ferramenta, processe seus dados e obtenha o resultado sem etapas desnecessárias.',selectTitle:'Escolha uma ferramenta',selectDescription:'Selecione entre 87 ferramentas para PDF, imagens, código, conversores e calculadoras.',processTitle:'Processe e veja o resultado',processDescription:'Muitas ferramentas processam os dados diretamente no navegador quando isso é compatível.',exportTitle:'Exporte na hora',exportDescription:'Baixe o resultado ou revise os dados imediatamente.',privacyBadge:'Arquitetura no navegador',privacyTitle:'Feito para processamento rápido e consciente da privacidade',privacyDescription:'As operações compatíveis podem ser executadas localmente no navegador, reduzindo a necessidade de enviar arquivos para um servidor.',privacyOne:'Privacidade em primeiro lugar',privacyOneDesc:'Arquivos compatíveis podem permanecer no seu dispositivo durante o processamento local.',privacyTwo:'Processamento local',privacyTwoDesc:'Conversões e ferramentas compatíveis usam APIs do navegador e WebAssembly quando aplicável.',privacyThree:'Grátis para usar',privacyThreeDesc:'Não é necessário criar uma conta paga para usar o conjunto atual de ferramentas.',faqBadge:'Perguntas comuns',faqTitle:'Perguntas frequentes',ctaTitle:'Pronto para simplificar suas tarefas digitais?',ctaDescription:'Use o Toolployee diretamente no navegador sempre que o processamento local for compatível.',pick:'Escolher uma ferramenta'},
  es:{badge:'Herramientas online gratuitas',title:'Todas las herramientas online gratuitas que necesitas.',accent:'Necesitas.',description:'Herramientas rápidas y seguras para PDF, imágenes, código, conversiones y cálculos directamente en tu navegador.',searchPlaceholder:'Buscar herramientas (ej.: comprimir imagen, Python, SIP)...',search:'Buscar',popular:'Herramientas populares',showing:'Mostrando',utilities:'herramientas',explore:'Explorar las 87 herramientas',workflowBadge:'Flujo sencillo',workflowTitle:'Tres pasos. Todo en el navegador.',workflowDescription:'Elige una herramienta, procesa tus datos y obtén el resultado sin pasos innecesarios.',selectTitle:'Elige una herramienta',selectDescription:'Selecciona entre 87 herramientas para PDF, imágenes, código, conversiones y calculadoras.',processTitle:'Procesa y obtén resultados',processDescription:'Muchas herramientas procesan los datos directamente en el navegador cuando es compatible.',exportTitle:'Exporta al instante',exportDescription:'Descarga el resultado o revisa los datos inmediatamente.',privacyBadge:'Arquitectura en el navegador',privacyTitle:'Diseñado para un procesamiento rápido y consciente de la privacidad',privacyDescription:'Las operaciones compatibles pueden ejecutarse localmente en el navegador, reduciendo la necesidad de enviar archivos a un servidor.',privacyOne:'Privacidad primero',privacyOneDesc:'Los archivos compatibles pueden permanecer en tu dispositivo durante el procesamiento local.',privacyTwo:'Procesamiento local',privacyTwoDesc:'Las conversiones compatibles usan APIs del navegador y WebAssembly cuando corresponde.',privacyThree:'Gratis para usar',privacyThreeDesc:'No necesitas una cuenta de pago para usar el conjunto actual de herramientas.',faqBadge:'Preguntas comunes',faqTitle:'Preguntas frecuentes',ctaTitle:'¿Listo para simplificar tus tareas digitales?',ctaDescription:'Usa Toolployee directamente en el navegador cuando el procesamiento local sea compatible.',pick:'Elegir una herramienta'},
  de:{badge:'Kostenlose Online-Tools',title:'Alle kostenlosen Online-Tools, die du brauchst.',accent:'Du brauchst.',description:'Schnelle und sichere Tools für PDF, Bilder, Code, Konvertierungen und Berechnungen direkt im Browser.',searchPlaceholder:'Tools suchen (z. B. Bild komprimieren, Python, SIP)...',search:'Suchen',popular:'Beliebte Tools',showing:'Angezeigt',utilities:'Tools',explore:'Alle 87 Tools entdecken',workflowBadge:'Einfacher Ablauf',workflowTitle:'Drei Schritte. Alles im Browser.',workflowDescription:'Tool auswählen, Daten verarbeiten und Ergebnis ohne unnötige Schritte erhalten.',selectTitle:'Tool auswählen',selectDescription:'Wähle aus 87 Tools für PDF, Bilder, Code, Konverter und Rechner.',processTitle:'Verarbeiten und Ergebnis sehen',processDescription:'Viele Tools verarbeiten Daten direkt im Browser, sofern dies unterstützt wird.',exportTitle:'Sofort exportieren',exportDescription:'Ergebnis herunterladen oder direkt prüfen.',privacyBadge:'Browser-Architektur',privacyTitle:'Für schnelle und datenschutzbewusste Verarbeitung entwickelt',privacyDescription:'Unterstützte Vorgänge können lokal im Browser ausgeführt werden, wodurch weniger Dateien an Server gesendet werden müssen.',privacyOne:'Datenschutz zuerst',privacyOneDesc:'Unterstützte Dateien können bei lokaler Verarbeitung auf deinem Gerät bleiben.',privacyTwo:'Lokale Verarbeitung',privacyTwoDesc:'Unterstützte Konvertierungen nutzen Browser-APIs und WebAssembly, wo sinnvoll.',privacyThree:'Kostenlos nutzbar',privacyThreeDesc:'Für das aktuelle Toolset ist kein kostenpflichtiges Konto erforderlich.',faqBadge:'Häufige Fragen',faqTitle:'Häufig gestellte Fragen',ctaTitle:'Bereit für einfachere digitale Aufgaben?',ctaDescription:'Nutze Toolployee direkt im Browser, wenn lokale Verarbeitung unterstützt wird.',pick:'Tool auswählen'},
  fr:{badge:'Outils en ligne gratuits',title:'Tous les outils en ligne gratuits dont vous avez besoin.',accent:'Vous avez besoin.',description:'Des outils rapides et sécurisés pour les PDF, images, code, conversions et calculs directement dans votre navigateur.',searchPlaceholder:'Rechercher un outil (ex. compresser une image, Python, SIP)...',search:'Rechercher',popular:'Outils populaires',showing:'Affichage de',utilities:'outils',explore:'Explorer les 87 outils',workflowBadge:'Flux simplifié',workflowTitle:'Trois étapes. Tout dans le navigateur.',workflowDescription:'Choisissez un outil, traitez vos données et obtenez le résultat sans étapes inutiles.',selectTitle:'Choisir un outil',selectDescription:'Choisissez parmi 87 outils PDF, image, code, conversion et calcul.',processTitle:'Traiter et obtenir le résultat',processDescription:'De nombreux outils traitent les données directement dans le navigateur lorsque cela est pris en charge.',exportTitle:'Exporter instantanément',exportDescription:'Téléchargez le résultat ou vérifiez-le immédiatement.',privacyBadge:'Architecture navigateur',privacyTitle:'Conçu pour un traitement rapide et respectueux de la confidentialité',privacyDescription:'Les opérations compatibles peuvent être exécutées localement dans le navigateur, limitant l’envoi de fichiers vers un serveur.',privacyOne:'Confidentialité d’abord',privacyOneDesc:'Les fichiers compatibles peuvent rester sur votre appareil pendant le traitement local.',privacyTwo:'Traitement local',privacyTwoDesc:'Les conversions compatibles utilisent les API du navigateur et WebAssembly lorsque nécessaire.',privacyThree:'Utilisation gratuite',privacyThreeDesc:'Aucun compte payant n’est requis pour l’ensemble actuel des outils.',faqBadge:'Questions courantes',faqTitle:'Questions fréquentes',ctaTitle:'Prêt à simplifier vos tâches numériques ?',ctaDescription:'Utilisez Toolployee directement dans le navigateur lorsque le traitement local est pris en charge.',pick:'Choisir un outil'},
  it:{badge:'Strumenti online gratuiti',title:'Tutti gli strumenti online gratuiti di cui hai bisogno.',accent:'Di cui hai bisogno.',description:'Strumenti rapidi e sicuri per PDF, immagini, codice, conversioni e calcoli direttamente nel browser.',searchPlaceholder:'Cerca strumenti (es. comprimi immagine, Python, SIP)...',search:'Cerca',popular:'Strumenti popolari',showing:'Visualizzati',utilities:'strumenti',explore:'Esplora tutti gli 87 strumenti',workflowBadge:'Flusso semplice',workflowTitle:'Tre passaggi. Tutto nel browser.',workflowDescription:'Scegli uno strumento, elabora i dati e ottieni il risultato senza passaggi inutili.',selectTitle:'Scegli uno strumento',selectDescription:'Scegli tra 87 strumenti per PDF, immagini, codice, conversioni e calcoli.',processTitle:'Elabora e ottieni il risultato',processDescription:'Molti strumenti elaborano i dati direttamente nel browser quando supportato.',exportTitle:'Esporta subito',exportDescription:'Scarica il risultato o controllalo immediatamente.',privacyBadge:'Architettura browser',privacyTitle:'Progettato per un’elaborazione rapida e attenta alla privacy',privacyDescription:'Le operazioni supportate possono essere eseguite localmente nel browser, riducendo l’invio di file a un server.',privacyOne:'Privacy prima di tutto',privacyOneDesc:'I file compatibili possono rimanere sul dispositivo durante l’elaborazione locale.',privacyTwo:'Elaborazione locale',privacyTwoDesc:'Le conversioni compatibili usano API del browser e WebAssembly quando applicabile.',privacyThree:'Gratuito',privacyThreeDesc:'Non serve un account a pagamento per usare l’attuale raccolta di strumenti.',faqBadge:'Domande comuni',faqTitle:'Domande frequenti',ctaTitle:'Pronto a semplificare le attività digitali?',ctaDescription:'Usa Toolployee direttamente nel browser quando l’elaborazione locale è supportata.',pick:'Scegli uno strumento'},
  ja:{badge:'無料オンラインツール',title:'必要な無料オンラインツールをすべて.',accent:'すべて.',description:'PDF、画像、コード、変換、計算に使える高速で安全なツールをブラウザで利用できます。',searchPlaceholder:'ツールを検索（例：画像圧縮、Python、SIP）...',search:'検索',popular:'人気のツール',showing:'表示中',utilities:'ツール',explore:'87個のツールをすべて見る',workflowBadge:'シンプルな流れ',workflowTitle:'3ステップ。すべてブラウザで。',workflowDescription:'ツールを選び、データを処理し、不要な手順なしで結果を取得します。',selectTitle:'ツールを選択',selectDescription:'PDF、画像、コード、変換、計算に対応する87個のツールから選べます。',processTitle:'処理して結果を確認',processDescription:'対応するツールでは多くの処理をブラウザ上で直接実行できます。',exportTitle:'すぐに出力',exportDescription:'結果をダウンロードまたはすぐに確認できます。',privacyBadge:'ブラウザ中心の設計',privacyTitle:'高速でプライバシーに配慮した処理',privacyDescription:'対応する処理はブラウザ内でローカル実行でき、サーバーへのファイル送信を減らせます。',privacyOne:'プライバシー優先',privacyOneDesc:'ローカル処理中、対応ファイルは端末に残ります。',privacyTwo:'ローカル処理',privacyTwoDesc:'対応する変換ではブラウザAPIやWebAssemblyを利用します。',privacyThree:'無料で利用',privacyThreeDesc:'現在のツールセットには有料アカウントは必要ありません。',faqBadge:'よくある質問',faqTitle:'よくある質問',ctaTitle:'デジタル作業をもっと簡単にしませんか？',ctaDescription:'ローカル処理に対応する場合は、Toolployeeをブラウザから直接利用できます。',pick:'ツールを選ぶ'},
  ko:{badge:'무료 온라인 도구',title:'필요한 모든 무료 온라인 도구.',accent:'모두.',description:'PDF, 이미지, 코드, 변환 및 계산을 위한 빠르고 안전한 도구를 브라우저에서 바로 사용하세요.',searchPlaceholder:'도구 검색 (예: 이미지 압축, Python, SIP)...',search:'검색',popular:'인기 도구',showing:'표시 중',utilities:'도구',explore:'87개 도구 모두 보기',workflowBadge:'간단한 흐름',workflowTitle:'세 단계. 모두 브라우저에서.',workflowDescription:'도구를 선택하고 데이터를 처리한 뒤 불필요한 단계 없이 결과를 확인하세요.',selectTitle:'도구 선택',selectDescription:'PDF, 이미지, 코드, 변환 및 계산을 위한 87개 도구 중에서 선택하세요.',processTitle:'처리하고 결과 확인',processDescription:'지원되는 경우 많은 도구가 브라우저에서 직접 데이터를 처리합니다.',exportTitle:'즉시 내보내기',exportDescription:'결과를 다운로드하거나 바로 확인하세요.',privacyBadge:'브라우저 중심 구조',privacyTitle:'빠르고 개인정보를 고려한 처리',privacyDescription:'지원되는 작업은 브라우저에서 로컬로 실행되어 서버로 파일을 보내는 필요를 줄일 수 있습니다.',privacyOne:'개인정보 보호 우선',privacyOneDesc:'로컬 처리 중 지원되는 파일은 기기에 남을 수 있습니다.',privacyTwo:'로컬 처리',privacyTwoDesc:'지원되는 변환은 브라우저 API와 WebAssembly를 활용합니다.',privacyThree:'무료 사용',privacyThreeDesc:'현재 도구 모음을 사용하는 데 유료 계정이 필요하지 않습니다.',faqBadge:'자주 묻는 질문',faqTitle:'자주 묻는 질문',ctaTitle:'디지털 작업을 더 간단하게 시작할까요?',ctaDescription:'로컬 처리가 지원되는 경우 Toolployee를 브라우저에서 바로 사용하세요.',pick:'도구 선택'},
  zh:{badge:'免费在线工具',title:'你需要的所有免费在线工具。',accent:'全部都有。',description:'直接在浏览器中使用快速、安全的 PDF、图片、代码、转换和计算工具。',searchPlaceholder:'搜索工具（例如：压缩图片、Python、SIP）...',search:'搜索',popular:'热门工具',showing:'显示',utilities:'个工具',explore:'探索全部 87 个工具',workflowBadge:'简单流程',workflowTitle:'三步完成。全部在浏览器中。',workflowDescription:'选择工具、处理数据并直接获得结果，无需多余步骤。',selectTitle:'选择工具',selectDescription:'从 87 个 PDF、图片、代码、转换和计算工具中选择。',processTitle:'处理并查看结果',processDescription:'在支持的情况下，许多工具会直接在浏览器中处理数据。',exportTitle:'立即导出',exportDescription:'下载结果或立即检查结果。',privacyBadge:'浏览器优先架构',privacyTitle:'为快速且注重隐私的处理而打造',privacyDescription:'支持的操作可以在浏览器本地运行，减少向服务器上传文件的需要。',privacyOne:'隐私优先',privacyOneDesc:'本地处理时，支持的文件可以保留在你的设备上。',privacyTwo:'本地处理',privacyTwoDesc:'支持的转换会在适用时使用浏览器 API 和 WebAssembly。',privacyThree:'免费使用',privacyThreeDesc:'使用当前工具集合无需付费账户。',faqBadge:'常见问题',faqTitle:'常见问题',ctaTitle:'准备好简化你的数字任务了吗？',ctaDescription:'支持本地处理时，可直接在浏览器中使用 Toolployee。',pick:'选择工具'},
  ru:{badge:'Бесплатные онлайн-инструменты',title:'Все бесплатные онлайн-инструменты, которые вам нужны.',accent:'Вам нужны.',description:'Быстрые и безопасные инструменты для PDF, изображений, кода, конвертации и расчётов прямо в браузере.',searchPlaceholder:'Поиск инструментов (например: сжать изображение, Python, SIP)...',search:'Поиск',popular:'Популярные инструменты',showing:'Показано',utilities:'инструментов',explore:'Открыть все 87 инструментов',workflowBadge:'Простой процесс',workflowTitle:'Три шага. Всё в браузере.',workflowDescription:'Выберите инструмент, обработайте данные и получите результат без лишних действий.',selectTitle:'Выберите инструмент',selectDescription:'Доступно 87 инструментов для PDF, изображений, кода, конвертации и расчётов.',processTitle:'Обработайте и получите результат',processDescription:'Многие инструменты обрабатывают данные непосредственно в браузере, если это поддерживается.',exportTitle:'Экспорт сразу',exportDescription:'Скачайте результат или проверьте его сразу.',privacyBadge:'Архитектура браузера',privacyTitle:'Для быстрой обработки с учётом конфиденциальности',privacyDescription:'Поддерживаемые операции могут выполняться локально в браузере, уменьшая необходимость отправки файлов на сервер.',privacyOne:'Конфиденциальность прежде всего',privacyOneDesc:'При локальной обработке поддерживаемые файлы могут оставаться на устройстве.',privacyTwo:'Локальная обработка',privacyTwoDesc:'Поддерживаемые конвертации используют API браузера и WebAssembly, где это применимо.',privacyThree:'Бесплатно',privacyThreeDesc:'Для текущего набора инструментов платная учётная запись не требуется.',faqBadge:'Частые вопросы',faqTitle:'Часто задаваемые вопросы',ctaTitle:'Готовы упростить цифровые задачи?',ctaDescription:'Используйте Toolployee прямо в браузере, когда поддерживается локальная обработка.',pick:'Выбрать инструмент'},
  ar:{badge:'أدوات مجانية عبر الإنترنت',title:'كل الأدوات المجانية عبر الإنترنت التي تحتاج إليها.',accent:'التي تحتاج إليها.',description:'أدوات سريعة وآمنة لملفات PDF والصور والكود والتحويلات والحسابات مباشرة في المتصفح.',searchPlaceholder:'ابحث عن أداة (مثل ضغط صورة، Python، SIP)...',search:'بحث',popular:'الأدوات الشائعة',showing:'عرض',utilities:'أدوات',explore:'استكشف الأدوات الـ87',workflowBadge:'سير عمل بسيط',workflowTitle:'ثلاث خطوات. كل شيء في المتصفح.',workflowDescription:'اختر أداة، عالج بياناتك، واحصل على النتيجة دون خطوات غير ضرورية.',selectTitle:'اختر أداة',selectDescription:'اختر من بين 87 أداة لملفات PDF والصور والكود والتحويل والحسابات.',processTitle:'عالج واحصل على النتيجة',processDescription:'تعالج العديد من الأدوات البيانات مباشرة في المتصفح عند دعم ذلك.',exportTitle:'تصدير فوري',exportDescription:'نزّل النتيجة أو راجعها مباشرة.',privacyBadge:'بنية تعتمد على المتصفح',privacyTitle:'مصممة للمعالجة السريعة مع مراعاة الخصوصية',privacyDescription:'يمكن تنفيذ العمليات المدعومة محليًا في المتصفح، مما يقلل الحاجة إلى إرسال الملفات إلى خادم.',privacyOne:'الخصوصية أولًا',privacyOneDesc:'يمكن أن تبقى الملفات المدعومة على جهازك أثناء المعالجة المحلية.',privacyTwo:'معالجة محلية',privacyTwoDesc:'تستخدم التحويلات المدعومة واجهات المتصفح وWebAssembly عند الحاجة.',privacyThree:'مجانية الاستخدام',privacyThreeDesc:'لا يلزم حساب مدفوع لاستخدام مجموعة الأدوات الحالية.',faqBadge:'أسئلة شائعة',faqTitle:'الأسئلة الشائعة',ctaTitle:'هل أنت مستعد لتبسيط مهامك الرقمية؟',ctaDescription:'استخدم Toolployee مباشرة في المتصفح عندما تكون المعالجة المحلية مدعومة.',pick:'اختيار أداة'},
  hi:{badge:'मुफ्त ऑनलाइन टूल्स',title:'आपको चाहिए सभी मुफ्त ऑनलाइन टूल्स.',accent:'सभी यहाँ हैं।',description:'PDF, इमेज, कोड, कन्वर्ज़न और कैलकुलेशन के लिए तेज़ और सुरक्षित टूल्स सीधे ब्राउज़र में।',searchPlaceholder:'टूल खोजें (जैसे: इमेज कंप्रेस, Python, SIP)...',search:'खोजें',popular:'लोकप्रिय टूल्स',showing:'दिखाए जा रहे हैं',utilities:'टूल्स',explore:'सभी 87 टूल्स देखें',workflowBadge:'आसान वर्कफ़्लो',workflowTitle:'तीन चरण। सब कुछ ब्राउज़र में।',workflowDescription:'टूल चुनें, डेटा प्रोसेस करें और बिना अनावश्यक चरणों के परिणाम पाएँ।',selectTitle:'टूल चुनें',selectDescription:'PDF, इमेज, कोड, कन्वर्टर और कैलकुलेटर के 87 टूल्स में से चुनें।',processTitle:'प्रोसेस करें और परिणाम पाएँ',processDescription:'जहाँ समर्थित है, कई टूल्स डेटा को सीधे ब्राउज़र में प्रोसेस करते हैं।',exportTitle:'तुरंत एक्सपोर्ट करें',exportDescription:'परिणाम डाउनलोड करें या तुरंत जाँचें।',privacyBadge:'ब्राउज़र-फर्स्ट आर्किटेक्चर',privacyTitle:'तेज़ और प्राइवेसी-सचेत प्रोसेसिंग के लिए बनाया गया',privacyDescription:'समर्थित ऑपरेशन ब्राउज़र में लोकल रूप से चल सकते हैं, जिससे सर्वर पर फाइल भेजने की जरूरत कम होती है।',privacyOne:'प्राइवेसी पहले',privacyOneDesc:'लोकल प्रोसेसिंग के दौरान समर्थित फाइलें आपके डिवाइस पर रह सकती हैं।',privacyTwo:'लोकल प्रोसेसिंग',privacyTwoDesc:'समर्थित कन्वर्ज़न में जरूरत के अनुसार ब्राउज़र API और WebAssembly का उपयोग होता है।',privacyThree:'मुफ्त उपयोग',privacyThreeDesc:'वर्तमान टूल सेट का उपयोग करने के लिए पेड अकाउंट जरूरी नहीं है।',faqBadge:'आम सवाल',faqTitle:'अक्सर पूछे जाने वाले सवाल',ctaTitle:'अपनी डिजिटल टास्क आसान करने के लिए तैयार हैं?',ctaDescription:'जहाँ लोकल प्रोसेसिंग समर्थित हो, Toolployee को सीधे ब्राउज़र में इस्तेमाल करें।',pick:'टूल चुनें'}
};

function icon(cat:string) {
  switch(cat) {
    case 'PDF': return <FileText className="h-5 w-5 text-violet-600 dark:text-violet-400"/>;
    case 'Image': return <ImageIcon className="h-5 w-5 text-pink-500 dark:text-pink-400"/>;
    case 'Compiler':
    case 'Developer': return <Code className="h-5 w-5 text-emerald-500 dark:text-emerald-400"/>;
    case 'Finance':
    case 'Calculators': return <Calculator className="h-5 w-5 text-indigo-500 dark:text-indigo-400"/>;
    case 'Converters': return <ArrowLeftRight className="h-5 w-5 text-cyan-500 dark:text-cyan-400"/>;
    case 'YouTube': return <Video className="h-5 w-5 text-rose-500 dark:text-rose-400"/>;
    default: return <Type className="h-5 w-5 text-violet-500"/>;
  }
}

export const dynamicParams = false;
export function generateStaticParams(){ return LOCALES.filter(x=>x.code!=='en').map(x=>({locale:x.code})); }

export default async function LocalizedHome({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: localeCode } = await params;
  const locale = getLocale(localeCode);
  if (!locale || locale.code==='en') return null;
  const ui = getLocalizedUi(locale.code);
  const copy = COPY[locale.code];
  const [query,setQuery]=useState('');
  const [category,setCategory]=useState('All');
  const [faq,setFaq]=useState<number|null>(null);
  const tools=useMemo(()=>TOOLS_REGISTRY.filter(t=>
    (category==='All'||t.category===category) &&
    (!query.trim()||t.name.toLowerCase().includes(query.toLowerCase()))
  ),[query,category]);

  return <main lang={locale.code} dir={locale.code==='ar'?'rtl':'ltr'} className="min-h-screen bg-zinc-50 dark:bg-zinc-950 text-zinc-900 dark:text-zinc-100">
    <Navbar />
    <section className="mx-auto max-w-5xl px-4 pt-8 sm:pt-14 pb-6 text-center">
      <div className="inline-flex items-center gap-2 rounded-full border border-violet-200 dark:border-violet-900/60 bg-violet-50 dark:bg-violet-950/40 px-3.5 py-1 text-[11px] font-bold text-violet-700 dark:text-violet-300 mb-6"><Sparkles className="h-3.5 w-3.5"/>{copy.badge}</div>
      <h1 className="text-3xl sm:text-5xl lg:text-6xl font-extrabold tracking-[-0.03em] text-zinc-950 dark:text-white max-w-4xl mx-auto leading-[1.14]">{copy.title}</h1>
      <p className="mt-4 text-xs sm:text-base text-zinc-600 dark:text-zinc-400 max-w-2xl mx-auto leading-relaxed">{copy.description}</p>
      <form className="mt-8 max-w-xl mx-auto flex items-center gap-2" onSubmit={e=>e.preventDefault()}>
        <div className="relative flex-1 rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 shadow-sm">
          <Search className="absolute left-4 top-3.5 h-4 w-4 text-zinc-400"/>
          <input value={query} onChange={e=>setQuery(e.target.value)} placeholder={copy.searchPlaceholder} className="w-full bg-transparent py-3 pl-11 pr-4 text-xs focus:outline-none text-zinc-900 dark:text-white placeholder:text-zinc-400"/>
        </div>
        <button className="rounded-2xl bg-violet-600 px-6 py-3 text-xs font-bold text-white">{copy.search}</button>
      </form>
    </section>

    <section className="mx-auto max-w-7xl px-4 sm:px-6 pt-6">
      <div className="flex items-center justify-start sm:justify-center gap-2 overflow-x-auto pb-4 no-scrollbar">
        <button onClick={()=>setCategory('All')} className={`whitespace-nowrap rounded-xl px-4 py-2 text-xs font-semibold ${category==='All'?'bg-violet-600 text-white':'bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800'}`}>{copy.popular}</button>
        {CATEGORIES.filter(c=>c!=='All').map(c=><button key={c} onClick={()=>setCategory(c)} className={`whitespace-nowrap rounded-xl px-4 py-2 text-xs font-semibold ${category===c?'bg-violet-600 text-white':'bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800'}`}>{getLocalizedCategoryLabel(c,locale.code)} {ui.toolsLabel}</button>)}
      </div>
      <div className="mt-4 mb-2 flex items-center justify-between"><p className="text-xs font-bold uppercase tracking-wider text-zinc-400">{copy.showing} {tools.length} {category==='All'?copy.popular:getLocalizedCategoryLabel(category,locale.code)} {copy.utilities}</p></div>
      <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
        {tools.slice(0,24).map((tool:ToolMeta)=><Link key={tool.slug} href={localizedToolPath(locale.code,tool.slug)} className="group flex items-start gap-3.5 rounded-2xl border border-zinc-200/90 dark:border-zinc-800/80 bg-white dark:bg-zinc-900 p-4 transition-all hover:shadow-md hover:border-violet-400 hover:-translate-y-0.5">
          <div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-violet-50 dark:bg-zinc-800/80 mt-0.5">{icon(tool.category)}</div>
          <div className="min-w-0"><h2 className="text-xs sm:text-sm font-bold truncate">{getLocalizedToolName(tool,locale.code)}</h2><span className="text-[10px] font-semibold text-violet-600 dark:text-violet-400 block mt-0.5">{getLocalizedCategoryLabel(tool.category,locale.code)} {ui.toolsLabel}</span><p className="mt-1 text-[11px] text-zinc-500 dark:text-zinc-400 line-clamp-1">{ui.browserLabel}</p></div>
        </Link>)}
      </div>
      {category==='All'&&!query&&<div className="mt-10 text-center"><Link href={'/'+locale.code+'/tools'} className="inline-flex items-center gap-2 rounded-2xl bg-zinc-900 dark:bg-white text-white dark:text-zinc-950 px-8 py-3.5 text-xs font-extrabold"><span>{copy.explore}</span><ArrowRight className="h-4 w-4"/></Link></div>}
    </section>

    <section className="mx-auto max-w-7xl px-4 sm:px-6 mt-24">
      <div className="text-center max-w-xl mx-auto mb-12"><span className="text-xs font-bold text-violet-600 dark:text-violet-400 uppercase tracking-widest">{copy.workflowBadge}</span><h2 className="mt-2 text-2xl sm:text-3xl font-extrabold">{copy.workflowTitle}</h2><p className="mt-2 text-xs sm:text-sm text-zinc-500 dark:text-zinc-400">{copy.workflowDescription}</p></div>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {[{n:'01',icon:<MousePointerClick className="h-5 w-5"/>,t:copy.selectTitle,d:copy.selectDescription},{n:'02',icon:<Cpu className="h-5 w-5"/>,t:copy.processTitle,d:copy.processDescription},{n:'03',icon:<Zap className="h-5 w-5"/>,t:copy.exportTitle,d:copy.exportDescription}].map((x,i)=><div key={x.n} className={`rounded-3xl border p-8 shadow-sm ${i===1?'border-violet-200 dark:border-violet-900/80 bg-violet-50/40 dark:bg-violet-950/20':'border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900/60'}`}><div className="flex items-center justify-between mb-6"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-violet-600 text-white font-black text-sm">{x.n}</span>{x.icon}</div><h3 className="text-base font-bold">{x.t}</h3><p className="mt-2 text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed">{x.d}</p></div>)}
      </div>
    </section>

    <section className="mx-auto max-w-7xl px-4 sm:px-6 mt-20">
      <div className="rounded-3xl border border-zinc-200 dark:border-zinc-800/80 bg-white dark:bg-zinc-900 p-8 sm:p-12 shadow-sm">
        <div className="max-w-2xl mx-auto text-center"><span className="inline-flex items-center gap-1.5 rounded-full border border-violet-200 dark:border-violet-900/60 bg-violet-50 dark:bg-violet-950/40 px-3 py-1 text-[11px] font-bold text-violet-700 dark:text-violet-300 uppercase tracking-wider"><ShieldCheck className="h-3.5 w-3.5"/>{copy.privacyBadge}</span><h2 className="mt-4 text-2xl sm:text-3xl font-extrabold">{copy.privacyTitle}</h2><p className="mt-2 text-xs sm:text-sm text-zinc-500 dark:text-zinc-400">{copy.privacyDescription}</p></div>
        <div className="mt-10 grid grid-cols-1 md:grid-cols-3 gap-6">{[{icon:<Lock className="h-5 w-5"/>,t:copy.privacyOne,d:copy.privacyOneDesc},{icon:<Zap className="h-5 w-5"/>,t:copy.privacyTwo,d:copy.privacyTwoDesc},{icon:<Cpu className="h-5 w-5"/>,t:copy.privacyThree,d:copy.privacyThreeDesc}].map((x,i)=><div key={i} className="rounded-2xl border border-zinc-100 dark:border-zinc-800 bg-zinc-50/60 dark:bg-zinc-950/40 p-6"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-100 dark:bg-violet-950/60 text-violet-600 mb-4">{x.icon}</div><h3 className="text-sm font-bold">{x.t}</h3><p className="mt-1.5 text-xs text-zinc-500 dark:text-zinc-400 leading-relaxed">{x.d}</p></div>)}</div>
        <div className="mt-8 pt-8 border-t border-zinc-200/60 dark:border-zinc-800/60 grid grid-cols-2 sm:grid-cols-4 gap-4 text-center"><div><p className="text-xl font-black text-violet-600">87</p><p className="text-[11px] font-semibold text-zinc-500 uppercase mt-0.5">{ui.toolsLabel}</p></div><div><p className="text-xl font-black text-violet-600">Local</p><p className="text-[11px] font-semibold text-zinc-500 uppercase mt-0.5">{copy.privacyTwo}</p></div><div><p className="text-xl font-black text-violet-600">Local</p><p className="text-[11px] font-semibold text-zinc-500 uppercase mt-0.5">{ui.browserLabel}</p></div><div><p className="text-xl font-black text-violet-600">$0</p><p className="text-[11px] font-semibold text-zinc-500 uppercase mt-0.5">{copy.privacyThree}</p></div></div>
      </div>
    </section>

    <section className="mx-auto max-w-4xl px-4 sm:px-6 mt-20"><div className="text-center mb-10"><span className="inline-flex items-center gap-1 text-xs font-bold text-violet-600 uppercase tracking-widest"><HelpCircle className="h-3.5 w-3.5"/>{copy.faqBadge}</span><h2 className="mt-2 text-2xl sm:text-3xl font-extrabold">{copy.faqTitle}</h2></div><div className="space-y-3">{[copy.selectDescription,copy.processDescription,copy.privacyOneDesc,copy.privacyThreeDesc].map((answer,i)=><div key={i} className="rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 overflow-hidden"><button type="button" onClick={()=>setFaq(faq===i?null:i)} className="flex w-full items-center justify-between p-5 text-left text-xs sm:text-sm font-bold"><span>{[copy.selectTitle,copy.processTitle,copy.privacyOne,copy.privacyThree][i]}</span><ChevronDown className={`h-4 w-4 ${faq===i?'rotate-180':''}`}/></button>{faq===i&&<div className="px-5 pb-5 text-xs sm:text-sm text-zinc-500 leading-relaxed">{answer}</div>}</div>)}</div></section>

    <section className="mx-auto max-w-7xl px-4 sm:px-6 mt-20 mb-20"><div className="relative overflow-hidden rounded-3xl bg-zinc-950 px-8 py-12 sm:px-16 sm:py-16 text-center text-white"><Layers className="h-10 w-10 text-violet-400 mx-auto mb-4"/><h2 className="text-2xl sm:text-4xl font-black">{copy.ctaTitle}</h2><p className="mt-3 text-xs sm:text-sm text-zinc-400">{copy.ctaDescription}</p><div className="mt-8 flex flex-wrap justify-center gap-3"><Link href={'/'+locale.code+'/tools'} className="rounded-2xl bg-violet-600 px-7 py-3 text-xs font-bold">{copy.explore}</Link><a href="#tools" className="rounded-2xl border border-zinc-800 bg-zinc-900 px-7 py-3 text-xs font-bold text-zinc-300">{copy.pick}</a></div></div></section>
    <Footer />
  </main>;
}
