// Generated by scripts/generate-localized-tool-seo.ts.
// This file is replaced by the localization workflow with static translations.
// Keeping an empty map here allows the project to build before the first generation run.
import type { LocaleCode } from '@/data/internationalSeo';
import type { ToolSeoContent } from '@/data/toolSeo';

export const GENERATED_LOCALIZED_TOOL_SEO: Partial<Record<LocaleCode, Record<string, ToolSeoContent>>> = {};
